### ISSUE TITLE
Ошибка в проверке уникальности номеров счетов Райффайзенбанка

### ISSUE THREAD

**Issue by alardus** [zenmoney/ZenPlugins#147]
Привет!
Похоже, что в плагине для Райффайзенбанка есть баг в механизме проверки уникальности номеров счетов. Плагин определяет уникальность по последним 4 цифрам номера, но не учитывает что номера счётов могут заканчиваться на один и тот же блок цифр, но отличаться блоком цифр в середине. Появление таких счетов в импортируемых данных приводит к тому, что подключение к банку останавливается с ошибкой "в импортированных данных есть одинаковые номера счетов". 

Единственный способ настроить подключение в этом случае - "пропускать" первый из найденных счётов с похожими номерами, но этот вариант так себе - баланс в этом случае не сойдётся. 

Возможное решение - сверять номера счетов полностью, а не по последним цифрам.

**Comment by skvav** [comment]
Спасибо за замечания! Плагин для Райффайзена собираемся переводить на новую версию API банка, тогда и внесем правки.

**Comment by alardus** [comment]
Класс, спасибо! А есть представление когда примерно должен сойтись плагин на новом апи?

**Comment by skvav** [comment]
Начали тестирование нового плагина. А можете привести пример таких номеров счетов, чтобы последние цифры были одинаковые? Интересно, где начинаются уникальные цифры. Не хочется  пихать в приложение весь длиннющий номер счета. Лучше чтобы id счета в нем выглядело более менее красиво для пользователя, что-то наподобие "234*4356". Потому надо знать где звездочки расставить.

**Comment by alardus** [comment]
Например:
40817810401001898257
40817840401000898257

**Comment by alardus** [comment]
Привет! Новый плагин нельзя проверить в деле еще?

**Comment by skvav** [comment]
@alardus Новый плагин уже выложен для всех и работает в качестве основного плагина Райфа. По вашей проблеме решение пока временно зависло. Пришлите, пожалуйста, лог со свежего плагина, тогда придумаем, что можно будет сделать.

**Comment by alardus** [comment]
Спасибо, посмотрел на новый плагин, проблема осталась - он точно также находит "одинаковые счета" и при попытке добавить их прекращает импорт. Текущий вариант решения работающий для меня - пропустить один из дублирующихся счетов при импорте.

**Comment by skvav** [comment]
@alardus Дело в том, что для всех мы не можем передавать номер счета целиком, это сломает синхронизацию другим пользователям. Потому есть вариант решения: если несколько счетов с одинаковыми последними 4-мя цифрами, то только в этом случае передаем в приложение полный номер счета. Но чтобы понять, где именно в новом плагине эти номера счетов, нужен от вас лог.

**Comment by alardus** [comment]
А как вынуть лог синхронизации из приложения, подскажите пожалуйста?

**Comment by skvav** [comment]
После синхронизации нажмите на шестеренку напротив подключения "Райффайзенбанк". Там будет кнопка "Отправить лог разработчикам"

**Comment by alardus** [comment]
Спасибо, отправил нужный кусок.

**Comment by skvav** [comment]
Интересно. Если у счетов одинаково заканчивается номер счета, но валюты при этом разные, то это не должно мешать работе. У вас как раз такой случай. Вероятно кроме этих двух счетов в полном логе есть еще какие-то с похожим номером счета? По урезанному логу сложно разобраться в проблеме.

**Comment by skvav** [comment]
В любом случае проверим еще раз такие случаи. Спасибо за лог!

**Comment by skvav** [comment]
@alardus если есть возможность, пришлите пожалуйста лог после 
`[debug] scrape call #1 { resolveValue:`
Можно только ту его часть, которая касается добавления счетов.

**Comment by alardus** [comment]
@skvav в логе вроде больше ничего похожего нет, но на всякий случай отправил лог со всеми счетами и картами которые он импортировал, без транзакций. Плюс ту часть, которая после `[debug] scrape call #1 { resolveValue:`

**Comment by skvav** [comment]
В логах видна еще кредитка, у которой такой же номер счета, судя по всему. Но лога по ней нет, потому что вы его вырезали :) https://sso.raiffeisen.ru/rest/card?alien=false

**Comment by alardus** [comment]
@skvav дослал, оно ниже по логу было, а я вырезал из первого блока :) Там как раз счет 40817810101000898597 и валюта рубль, а у другой карты с такой же валютой - счет 40817810401001898597

**Comment by skvav** [comment]
Спасибо! Добавили обработку таких случае в плагин. Проверьте, должно теперь работать. Перед этим верните все счета в синхронизацию (по нажатию на шестеренку подключения Райффайзенбанк).

**Comment by alardus** [comment]
Да, теперь импорт проходит корректно, все счета и карты добавляются. Спасибо!
