### ISSUE TITLE
Ошибка при синхронизации по овердрафтам Промсвязьбанка

### ISSUE THREAD

**Issue by whattahaylie** [zenmoney/ZenPlugins#155]
День добрый! Надеюсь хоть здесь найдутся те, кто исправит косяк с остатками по овердрафтным счетам Промсвязьбанка.
При синхронизации с ИБ, если карта с кредитным лимитом, сумма лимита автоматически плюсуется к остаткам. Т.е. если лимит по карте 10000, остаток 3000, в балансе автоматически выставляется 13000, хотя по факту  - 7000. Приходится каждый раз руками исправлять остатки и минусовать сумму овердрафта, чтобы цифры были реальнее. + при таких синхронизациях происходит большое количество корректировок, которые искажают статистику. 
А ещё в выписках ПСБ по овердрафтным счетам отображаются такие операции как "выдача кредита" и "погашение основного долга". В выписке в сумме они дают 0, но при синхронизации с Дзеном вносят путаницу и плодят лишние операции без категории.
Если найдётся человек, готовый это поправить, буду безмерно благодарна! В тех поддержку приложения писала, отправили сюда 😀

**Comment by skvav** [comment]
Здравствуйте! Спасибо за описание ошибки. Пока внести правки мы не можем, так как у нас данных для воспроизведения. Потому нужна ваша помощь. Синхронизируйтесь в приложении с банком еще раз и пришлите нам, пожалуйста, лог плагина. Это можно сделать, если нажать на шестеренку напротив подключения Промсвязьбанк на экране счетов и выбрать пункт "Отправить лог разработчикам".

**Comment by whattahaylie** [comment]
Готово!

**Comment by skvav** [comment]
@whattahaylie внесли правки в плагин, попробуйте синхронизироваться сейчас. Балансы должны быть верные. А операции "выдача кредита" и "погашение основного долга" теперь будут просто пропускаться.

**Comment by whattahaylie** [comment]
Все работает! Спасибо огромное!!! Наконец то есть адекватный менеджер финансов, в который не надо все расходы забивать руками!!! Отправлено с моего устройства Huawei-------- Исходное сообщение --------Тема: Re: [zenmoney/ZenPlugins] Ошибка при синхронизации по овердрафтам Промсвязьбанка (#155)От: Konstantin Sychkin Кому: zenmoney/ZenPlugins Копия: whattahaylie ,Mention @whattahaylie внесли правки в плагин, попробуйте синхронизироваться сейчас. Балансы должны быть верные. А операции "выдача кредита" и "погашение основного долга" теперь будут просто пропускаться.

—You are receiving this because you were mentioned.Reply to this email directly, view it on GitHub, or mute the thread.


  
  




{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/zenmoney/ZenPlugins","title":"zenmoney/ZenPlugins","subtitle":"GitHub repository","main_image_url":"https://cloud.githubusercontent.com/assets/143418/17495839/a5054eac-5d88-11e6-95fc-7290892c7bb5.png","avatar_image_url":"https://cloud.githubusercontent.com/assets/143418/15842166/7c72db34-2c0b-11e6-9aed-b52498112777.png","action":{"name":"Open in GitHub","url":"https://github.com/zenmoney/ZenPlugins"}},"updates":{"snippets":[{"icon":"PERSON","message":"@skvav in #155: @whattahaylie внесли правки в плагин, попробуйте синхронизироваться сейчас. Балансы должны быть верные. А операции \"выдача кредита\" и \"погашение основного долга\" теперь будут просто пропускаться."}],"action":{"name":"View Issue","url":"https://github.com/zenmoney/ZenPlugins/issues/155#issuecomment-368207467"}}}

**Comment by skvav** [comment]
@whattahaylie Отлично. Если вдруг возникнут еще проблемы, сообщайте о них, постараемся решить :)
