### ISSUE TITLE
Почините итерацию с приват банком!

### ISSUE THREAD

**Issue by storytime** [zenmoney/ZenPlugins#156]

**Comment by skvav** [comment]
Добрый день! Извиняемся за долгий ответ. Но есть радостная новость: сделали новый плагин Приватбанка. Пока доступен только для бета-тестеров. Чтобы поучаствовать в бета-тестировании напишите свой логин в Дзен-мани в чат приложения либо на support@zenmoney.ru

**Comment by skvav** [comment]
Выложили новый плагин для Приватбанка. Доступен из мобильных приложений.
