### ISSUE TITLE
Unicredit синхронизация

### ISSUE THREAD

**Issue by IvanGavrilenko** [zenmoney/ZenPlugins#157]
Плагина Юникредита достает только итоговую сумму по счету (и по расчетному счету и по картам), без разбивки на транзакции - то есть после покупки пирожка за 30р и игрушки за 200р в разных точках после автосинхронизации я увижу только одну транзакцию на 230р с комментом "Автоматическая корректировка баланса счета"

**Comment by skvav** [comment]
Выложили новую версию плагина. Если будут ошибки в ней, присылайте логи или пул-реквесты :)
