### ISSUE TITLE
Не работает импорт из Приорбанка

### ISSUE THREAD

**Issue by alparo** [zenmoney/ZenPlugins#158]
`[ZP] Exception: __ [TDA] Wrong transaction null date format
[ZP] Call stack:
at ZenMoney.Error (<anonymous>:21:29)
at <anonymous>:1:1
at /data/user/0/ru.zenmoney.androidsub/files/ZenPlugin/priorbank/index.js:21871:26
at tryCallOne (/data/user/0/ru.zenmoney.androidsub/files/ZenPlugin/priorbank/index.js:19812:12)
at /data/user/0/ru.zenmoney.androidsub/files/ZenPlugin/priorbank/index.js:19898:15
at ./src/asapRawMock.js.module.exports (/data/user/0/ru.zenmoney.androidsub/files/ZenPlugin/priorbank/index.js:21776:5)
at handleResolved (/data/user/0/ru.zenmoney.androidsub/files/ZenPlugin/priorbank/index.js:19888:3)
at handle (/data/user/0/ru.zenmoney.androidsub/files/ZenPlugin/priorbank/index.js:19884:3)
at Promise../node_modules/promise/lib/core.js.Promise.then (/data/user/0/ru.zenmoney.androidsub/files/ZenPlugin/priorbank/index.js:19852:3)
at adaptedAsyncFn (/data/user/0/ru.zenmoney.androidsub/files/ZenPlugin/priorbank/index.js:21866:36)`

**Comment by Metallium** [comment]
для воспроизведения хотелось бы весь иметь весь лог работы плагин (можно прислать на email)

**Comment by alparo** [comment]
пару дней назад импорт перестал вываливать ошибку. Но и операций новых по карте не было. Я еще понаблюдаю и потом отпишусь.

**Comment by Metallium** [comment]
плагин импортирует данные за недельку, просто съехало окно :)
если интересно - можно удалить подключение и создать заново, при этом будет синхронизироваться начиная с указанной в настройках даты

**Comment by alparo** [comment]
Нет. Рисковать не хочу. :)
Я трижды отправлял логи на вышеуказанный имейл. Если у вас есть к нему доступ, то посмотрите письмо с темой "ZenPlugin [a4.8.2.172919] [priorbank 10]" от 5го марта.

**Comment by Metallium** [comment]
импорт старается быть идемпотентным (дублей точно не должно быть если суммы руками не менялись), так что можно спокойно пробовать пересоздавать подключение :) (такое все равно рано или поздно произойдет, например при смене устройства)

не знал что есть письмо, гляну, спасибо

**Comment by Metallium** [comment]
кое-что поправили
попробуйте провести какую-нибудь транзакцию (да хоть перевод со счета на счет) и синхронизироваться

**Comment by alparo** [comment]
Сегодня как раз капнула зарплата. Операция добавилась только что без каких-либо проблем! Спасибо. Будем считать, что теперь все работает. В любом случае я теперь знаю куда писать.

Оффтоп: прикрутите импорт из МТБанка или хотя бы Технобанка? Готов даже сколько-нибудь донейтнуть. Если это возможно, напишите, пожалуйста, мне на тот имейл с которого логи пришли.

**Comment by Metallium** [comment]
Касаемо плагинов для любых других банков: если вы разработчик - мы готовы помочь персонально, отвечая на возникающие в ходе разработки плагина вопросы.

Вы создаете плагин, мы получаем обратную связь и корректируем документацию и примеры, делая разработку плагинов доступнее 🙂
