### ISSUE TITLE
ZenMoney.addAccount() не создает счет с типом 'checking'

### ISSUE THREAD

**Issue by Ryadnov** [zenmoney/ZenPlugins#19]
Пример кода тут https://github.com/zenmoney/ZenPlugins/blob/master/plugins/rocketbank/main.js#L94-L101

При импорте Андроид приложение НЕ предлагает создать данный счет
Если изменить тип на "ccard", то все хорошо

**Comment by skvav** [comment]
Да, это баг в версии приложения для Андроид <= 4.3. В 4.4 поправили.

**Comment by Ryadnov** [comment]
ОК
