### ISSUE TITLE
[Альфа-банк 41] Ошибка плагина при синхронизации

### ISSUE THREAD

**Issue by StasOmel** [zenmoney/ZenPlugins#214]
Синхронизация перестала работать.
После ввода смс кода ошибка:
typeerror invalid attempt to destructure non-iterable instance
Кнопку сообщить об ошибке нажал и отправил лог.
![j7u0_mz4amc](https://user-images.githubusercontent.com/432018/41593651-7b677c6a-73c9-11e8-8db7-78d992559b9d.jpg)
Возможно это связано с тем что сейчас на руках две карты: старая и такая же перевыпущенная. Обе отображаются в веб банкинге.

**Comment by Metallium** [comment]
А номер карты пытаетесь вводить старый или новый?

**Comment by StasOmel** [comment]
Номера у карт одинаковые. Разница в сроках действия.  Пробовал оба варанта.

вт, 19 июн. 2018 г. в 20:30, Nikita <notifications@github.com>:

**Comment by Metallium** [comment]
в https://github.com/zenmoney/ZenPlugins/pull/212/commits/0cde2b42979df51dfee0174bf5d6ff0cb1c208cf я немного расширил логгирование, чтобы понять, что там не так под капотом :)

**Comment by StasOmel** [comment]
Теперь больше всего выдаёт. Отправил на support@zenmoney.ru

**Comment by StasOmel** [comment]
Версия 43 не доходит до ввода пароля: "Пожалуйста запросите пароль повторно" (постоянно) или "Некоректные данные. Пожалуйста попробуйте ещё раз" (пару раз).

**Comment by Metallium** [comment]
Воспроизвести локально проблему без наличия ваших учетных данных затруднительно, а передача таких данных кому-либо является небезопасным.

Если у вас есть желание (как у разработчика) разобраться, в чём уникальность именно вашей ситуации - мы можем помочь.

Если нет - в относительно недалеком времени auth будет переделан на webview, и есть вероятность что ваша проблема решится.

**Comment by StasOmel** [comment]
Конкретно сейчас оно даже не доходит до ввода пароля, причём тоже самое через родное приложение от альфы. Видимо сейчас проблема у банка.

**Comment by Metallium** [comment]
возможно дело в нескольких незавершенных попытках регистрации?
можно попробовать обратиться в поддержку банка и добиться успешного логина в мобильном приложении

**Comment by StasOmel** [comment]
По пин коду оно логинится. Проблема у них именно в логине по карте (если забыл пин код).

**Comment by Metallium** [comment]
По пинкоду это если логиниться через номер счёта вместо номера карты?

**Comment by StasOmel** [comment]
Нет, по номеру счёта это отдельное. Именно по пинкоду (5 цифр которые они попросили придумать) как в приложении сбербанка.

**Comment by Metallium** [comment]
А можете поделиться скриншотом, где в мобильном приложении вы нашли возможность входа через пин?

**Comment by StasOmel** [comment]
![screenshot_2018-06-26-14-43-14](https://user-images.githubusercontent.com/432018/41909397-97ff0aa6-794f-11e8-9d7e-0d3d86203fbd.png)
Может  у вас не самая новая версия

**Comment by erictheswift** [comment]
недостаточно данных для воспроизведения;
буду рад помочь вам если решитесь заняться отладкой самостоятельно

**Comment by sromanenko** [comment]
Готов помочь с отладкой. Моя проблема похоже связана с тем, что карту перевыпустили и с новыми реквизитами выдает немного другую ошибку: "Альфа-Банк[58] Ошибка в импорте из банка. Отправьте отчёт, чтобы мы смогли найти и исправить ошибку". Что нужно сделать чтобы снять лог?

**Comment by erictheswift** [comment]
@sromanenko если хотите дискуссии — откройте пожалуйста отдельный issue т.к. этот изначально был посвящён проблеме с auth.

В вашем случае быстрее всего фикс проблемы появится если вы пришлёте лог синхронизации из приложения для воспроизведения.

В изначальной проблеме issue стартера (@StasOmel), из-за специфики auth, sanitized лог не сильно помог разобраться и мной была предложена сессия самостоятельной/совместной отладки.

**Comment by StasOmel** [comment]
Перестал пользоваться альфабанком, но сейчас специально проверил с версией плагина 58 и ошибок нет.
