### ISSUE TITLE
[Альфабанк] Не загружаются комментарии к транзакциям

### ISSUE THREAD

**Issue by mrdarksys** [zenmoney/ZenPlugins#216]
Доброго времени суток.
При синхронизации с Альфабанком не загружаются комментарии к операциям.
**Было**:
Есть счёт, где за неделю происходит до 250 операций (инвестиционный). Распознание их категорий было настроено правилами на основе комментариев. Для корректной синхронизации и чтобы не терялись - загружал их через импорт csv файлом.
**Стало**:
Попробовал новую синхронизацию, но отсутствие комментириев привело к полному хаосу и некорректному случайному распознованию операций.

**Comment by Metallium** [comment]
Отправьте разработчикам из приложения лог синхронизации (содержащей транзакцию с неимпортированным комментарием) + пожалуйста включите в письмо ссылку на этот pull request - постараемся поправить.

**Comment by mrdarksys** [comment]
12 июля отправил выгрузку, со ссылкой на эту проблему. Лог синхронизации не отправлялся (приложение падало, при каждой попытке).

**Comment by skvav** [comment]
Если проблема еще актуальна - пересоздайте тикет, пожалуйста.
