### ISSUE TITLE
Лицензия?

### ISSUE THREAD

**Issue by notpushkin** [zenmoney/ZenPlugins#220]
Было бы неплохо, если выложите этот репозиторий под открытой лицензией :) Но если это невозможно, стоит как минимум добавить CLA, разрешающий использование законтрибьюченного кода собственно в zenmoney.

В любом случае, понадобится согласие [всех текущих контрибьюторов](https://github.com/zenmoney/ZenPlugins/graphs/contributors) (кроме тех, чьего кода уже нет в master, если такие найдутся).

По умолчанию PR на гитхабе не разрешают использование кода каким-либо образом, если в репозитории нет лицензии: [GitHub ToS, section D](https://help.github.com/articles/github-terms-of-service/#d-user-generated-content).

**Comment by zenmoney** [comment]
Привет! Перешли на GNU GPLv3.
