### ISSUE TITLE
[belswissbank] Ошибка получения транзакций: unknown transactionType

### ISSUE THREAD

**Issue by alex-shevchuk** [zenmoney/ZenPlugins#236]
Банк ввёл новый тип операции "Списание".
Каждый месяц первого числа списываются деньги за смс оповещения:
```
transactionType: "Списание",
transactionCategory: "Request"
```

**Comment by Metallium** [comment]
просто добавьте знак операции сюда:
https://github.com/zenmoney/ZenPlugins/blob/master/src/plugins/belswissbank/BSB.js#L17

**Comment by erictheswift** [comment]
fixed in https://github.com/zenmoney/ZenPlugins/pull/260/files
