### ISSUE TITLE
[vtb] не загружаются транзакции мастер счета и привязанных к нему карт

### ISSUE THREAD

**Issue by BaronKorfRus** [zenmoney/ZenPlugins#243]
1. Синхронизация проходит, но по основному мастер счету и 4 картам не показывает операции, только корректировки, история  операций не загрузилась.

2. Перемещения между мастер счетом и депозитом отмечается как _Корректировка_ на мастер счете и _Без категории_ на депозите, а не перемещение.

3. По депозитам историю операций подгрузил и показывает их как траты/доходы _Без категории_, что наверно верно, в отличии от п1

Лог выслал 12.09 в 9.00 на адрес поддержки

**Comment by prdetective** [comment]
Была такая проблема, когда мне выпустили ещё одну карту, но я ее ещё не получил и не активировал. Висела в приложении втб готовая к получению пин кода. 

Приехал, карту забрал, пин код получил, карту активировал, и синхронизация сразу заработала правильно.

**Comment by BaronKorfRus** [comment]
> Была такая проблема, когда мне выпустили ещё одну карту, но я ее ещё не получил и не активировал. Висела в приложении втб готовая к получению пин кода.
> 
> Приехал, карту забрал, пин код получил, карту активировал, и синхронизация сразу заработала правильно.

Спасибо! Именно это и было, у меня висела карта не выданная (статус Изготовлена), очень давно, я особо не парился. Как прочитал совет, пошел и закрыл ее, сразу всё заработало! Напишу на портале, чтобы добавили в описание синхронизации., в логах этой карты вообще не видно
