### ISSUE TITLE
[Docs] Deprecated APIs

### ISSUE THREAD

**Issue by loginov-rocks** [zenmoney/ZenPlugins#247]
I didn't managed to get V1, V2, S1, R1 APIs working with OAuth authorization and I haven't found anything about another types of authZ. It would be better to remove or add deprecation tags for these APIs.

- They are mentioned here http://developers.zenmoney.ru/index.html
- REST page is missing http://developers.zenmoney.ru/index.html#!/rest/
- "Обсуждение" link transfers user to https://zenmoney.ru website

It also would be much better to document proper way to authorize user, pages above didn't help as well as this topic https://support.zenmoney.ru/communities/1/topics/489-token-k-api - I got authorization working only after digging into https://github.com/Ryadnov/zenmoney-php-api-library code.

So if I understand correctly the only source of truth is this page https://github.com/zenmoney/ZenPlugins/wiki/ZenMoney-API

Thanks!

**Comment by skvav** [comment]
Thank you! We changed link to API documentation on Zenmoney main page. Now it points to actual docs on GitHub.

**Comment by SleepWalker** [comment]
Hello, I've tried to follow the docs from this repo, but I can't get through token request step. I'm getting the following error:

```json
{
  "error": "invalid_grant"
}
```

Originally I'm logging in through the google account, but I've also tried to set the password up and use it for oauth, but the result is the same.

Here is an example of request:

```bash
curl -X POST \
  -H 'Content-Type: application/x-www-form-urlencoded' \
  -d 'grant_type=authorization_code&client_id=123&client_secret=123&code=444&redirect_uri=http%3A%2F%2Fexample.com%2Fcb%2F123' \
  https://api.zenmoney.ru/oauth2/token -i
```

Looks like everything is matching the docs, including `grant_type`, but I'm constantly getting the above error.

**Comment by trycontrolmymind** [comment]
@skvav same answer with google account
