### ISSUE TITLE
[tochka] incorrect operarion date

### ISSUE THREAD

**Issue by kai11** [zenmoney/ZenPlugins#251]
АПИ точки возвращает операцию только после полного завершения - те через два-три дня.
при этом платеж попадает в ZenMoney на ту дату, которая указана в апи - те на день или два позже. 
В примере ниже дата 04.12 а операция проведена 03.12.
     { id: '1;334903943',
       date: '04.12.2018',
       incomeAccount: 'ххх',
       outcomeAccount: 'ххх',
       payee: 'ПАО БАНК "ФК ОТКРЫТИЕ"',
       comment: 'Покупка товара(Терминал:GANDI.NET, 121 2ND STREET, 317-039-3748, US,дата операции:03/12/2018 04:22,на сумму:15.5(840),карта 5140********3810)\n',
       income: 0,
       outcome: 1035.4 },

Можно ли использовать даты их описания операции?

**Comment by kai11** [comment]
Кстати, поэтому постоянно возникают операции по корректированию баланса - состочние счета текущее (сколько доступно всего) а транзакции только полностью проведенные.
Эту коррекцию тоже нужно отключить

**Comment by skvav** [comment]
Не прошло и года как поправили :) Должна распознаваться дата из комментария.
