### ISSUE TITLE
[Priorbank] Priorbank BY Не работает подключение к интернет-банку

### ISSUE THREAD

**Issue by tikhanovichA** [zenmoney/ZenPlugins#267]
При попытке подключить Приорбанк на IOS, постоянно ошибка о неверном логине или пароле. Хотя логин и пароль на 100% верны. Подключаюсь с ними к интернет-банкингу напрямую без каких-то проблем.

**Comment by erictheswift** [comment]
На всякий случай напомню, что у приора два пароля (для входа и для платежей).
Попробуйте оставить в логине/пароле только alphanumerics.
Если всё еще не работает — отладить частную проблему с auth можете только вы самостоятельно. Могу лишь что-нибудь посоветовать в личной беседе.

**Comment by tikhanovichA** [comment]
Спасибо за ответ. 
Насчет пароля, да, использую имеено для входа который. Поменял логин и пароль только из букв и цифр, но не помогло. Все таже ошибка. 
Буду пробовать самостотельно дебажить. Если что, стукнусь за помощью

**Comment by vetheslav** [comment]
@erictheswift @skvav  Может закроем? Т.к. синхронизация на iOS работает

**Comment by tikhanovichA** [comment]
Да, сейчас всё ок!
