### ISSUE TITLE
[raiffeisen] Неверно корректируется баланс кредитной карты

### ISSUE THREAD

**Issue by alexeymalakhov** [zenmoney/ZenPlugins#268]
Добрый день!

Райффайзенбанк Россия, при импорте транзакций по кредитной карте, на которой установлен суточный расходный лимит, zenmoney добавляет автоматическую корректировку баланса счёта без учёта такого лимита.

На примере скриншота плагин берёт Кредитный лимит, вычитает из него Доступный остаток и делает корректировку счёта. Однако райф доступный остаток отображает с учётом установленного суточного лимита (в моём случае - 15000 руб, хотя по факту потратить я могу больше).

Корректнее (для случаев как с установленным суточным лимитом так и для случаев когда он не установлен) было бы считать доступный баланс как 
Кредитный лимит - задолженность на начало периода + всего поступлений - всего списаний - зарезервировано.

![raiff](https://user-images.githubusercontent.com/17816672/53325777-20350780-38f5-11e9-8ae0-8c5059fc1ee9.png)

**Comment by skvav** [comment]
Поправили обработку корректировок в приложении.
