### ISSUE TITLE
[МТбанк]

### ISSUE THREAD

**Issue by vetheslav** [zenmoney/ZenPlugins#274]
Привет, спасибо за интеграцию МТбанка. Сегодня пытался синхронизироваться и подключение вылетает с ошибкой "call anonymous with args".
Я готов выслать полный лог ошибки в личное сообщение, т.к. там много личных данных.
@efan, Вы сможете помочь?
Мой телеграм: @vetheslav

**Comment by efan** [comment]
@vetheslav там есть проблема с датами на ios при конвертации транзакций, подробнее тут: https://github.com/zenmoney/ZenPlugins/pull/273

**Comment by vetheslav** [comment]
@efan проблема решается в этом ПР: https://github.com/zenmoney/ZenPlugins/pull/276

**Comment by jonny3D** [comment]
Подключение к МТБанку обновили. Проверьте, пожалуйста. Если будут замечания, пишите, будем решать 🙂

**Comment by efan** [comment]
@jonny3D У меня все работает, круто, спасибо.
