### ISSUE TITLE
[ВТБ] Ошибка плагина при синхронизации

### ISSUE THREAD

**Issue by qstalker** [zenmoney/ZenPlugins#279]
сломалась синхронизация с ВТБ
ZenPlugin [i3.4.0.26020] [vtb24 115]

**Comment by qstalker** [comment]
![IMG_2515](https://user-images.githubusercontent.com/11345681/55673641-44501500-58b3-11e9-9577-d97cb47fce4b.PNG)

**Comment by qstalker** [comment]
Отчет отправлял пару раз, ошибка вылезает сразу после ввода пин кода, который приходит от банка

**Comment by trotux** [comment]
У меня наблюдается аналогичная проблема.

**Comment by skvav** [comment]
Внесли правки, должно теперь работать
