### ISSUE TITLE
[МТБанк] Корректировки в транзакциях, где поле balance пустое

### ISSUE THREAD

**Issue by alparo** [zenmoney/ZenPlugins#288]
Начиная с 14 апреля в логах синхронизации с МТБанк иногда появляются записи, где поле balance пустое. Такие транзакции появляются в Дзен-мани как Корректировки. Сейчас МТБанк готовится к какому-то громадному IT обновлению с 4 по 10 мая. Возможно с этим связаны проблемы. Вот для примера две транзакции. Одна обработалась без проблем, на месте второй возникла корректировка. Может, сможете починить, чтобы транзакции добавлялись как надо? Спасибо!

             { amount: '66.03',
               balance: '524.42',
               cardPan: '535104******3752',
               curr: 'BYN',
               debitFlag: '0',
               description: 'Оплата товаров и услуг',
               error: '',
               operationDate: '2019-04-18',
               orderStatus: '1',
               place: 'D-R "OSTROV CHISTOTY"     / MINSK         / BY',
               status: 'T',
               transAmount: '66.03',
               transDate: '2019-04-16 20:29:39' },
             { amount: '6.66',
               balance: '',
               cardPan: '535104******3752',
               curr: 'BYN',
               debitFlag: '0',
               description: 'Оплата товаров и услуг',
               error: '',
               operationDate: null,
               orderStatus: '2',
               place: 'PT SHOP GALAMART          / MINSK         / BY',
               status: 'A',
               transAmount: '6.66',
               transDate: '2019-04-18 11:45:39' },

**Comment by vetheslav** [comment]
@alparo большое спасибо, фикс вот тут: https://github.com/zenmoney/ZenPlugins/pull/289/files

**Comment by alparo** [comment]
Не за что. :)
У меня нет возможности пока протестировать - отключил синхронизацию до тех пор, пока банк не проведет обновления базы. Оставлю тикет пока открытым. Если считаете, что его нужно закрыть - напишите мне или сами закройте если это так работает.
