### ISSUE TITLE
[Альфабанк Беларусь] Неверный статус устройства NOT_AUTHORIZED

### ISSUE THREAD

**Issue by alparo** [zenmoney/ZenPlugins#292]
Проблема началась сегодня. Частота синхронизации выставлена в 20 минут. При этом родное приложение insync.by продолжает работать.
Не знаю как я могу еще помочь кроме как скинуть сюда лог. Если могу еще что-то сделать - скажите.

> [log] call anonymous with args: { preferences: {},
  fromDate: Fri Apr 19 2019 00:00:00 GMT+0300 (+03),
  toDate: null,
  isFirstRun: false }
[debug] request { method: 'POST',
  url: 'https://insync2.alfa-bank.by/mBank256/v5/CheckDeviceStatus?locale=ru',
  headers: 
   { Accept: 'application/json, text/plain, */*',
     'Content-Type': 'application/json; charset=UTF-8',
     'X-Client-App': 'Android/5.4.1',
     'User-Agent': 'okhttp/3.12.0' },
  body: { deviceId: '<string[36]>', locale: 'ru' } }
[debug] response { status: 200,
  url: 'https://insync2.alfa-bank.by/mBank256/v5/CheckDeviceStatus?locale=ru',
  headers: 
   { 'cache-control': 'no-cache, no-store, max-age=0, must-revalidate',
     'content-length': '352',
     'content-type': 'application/json;charset=UTF-8',
     date: 'Wed, 24 Apr 2019 14:25:04 GMT',
     expires: '0',
     pragma: 'no-cache',
     server: 'Apache-Coyote/1.1',
     'x-content-type-options': 'nosniff',
     'x-frame-options': 'DENY',
     'x-xss-protection': '1; mode=block' },
  body: 
   { status: 'LOCKED',
     message: 'Мы заблокировали приложение. Вы можете разблокировать его в «Альфа-Клике» (Настройки>Безопасность), в онлайн-чате или контакт-центре',
     preAuthZone: false,
     timeout: 300,
     isCredit: false },
  ms: 232 }
[debug] request { method: 'POST',
  url: 'https://insync2.alfa-bank.by/mBank256/v5/Authorization?locale=ru',
  headers: 
   { Accept: 'application/json, text/plain, */*',
     'Content-Type': 'application/json; charset=UTF-8',
     'X-Client-App': 'Android/5.4.1',
     'User-Agent': 'okhttp/3.12.0' },
  body: 
   { deviceId: '<string[36]>',
     deviceName: 'ZenMoney Plugin',
     isResident: true,
     login: '<string[14]>',
     screenHeight: 1794,
     screenWidth: 1080 } }
[debug] response { status: 200,
  url: 'https://insync2.alfa-bank.by/mBank256/v5/Authorization?locale=ru',
  headers: 
   { 'cache-control': 'no-cache, no-store, max-age=0, must-revalidate',
     'content-length': '101',
     'content-type': 'application/json;charset=UTF-8',
     date: 'Wed, 24 Apr 2019 14:25:38 GMT',
     expires: '0',
     pragma: 'no-cache',
     server: 'Apache-Coyote/1.1',
     'x-content-type-options': 'nosniff',
     'x-frame-options': 'DENY',
     'x-xss-protection': '1; mode=block' },
  body: 
   { message: 'Неверный статус устройства',
     status: 'NOT_AUTHORIZED' },
  ms: 115 }
[error] anonymous call rejected with [Error: Ответ банка: Неверный статус устройства] 
(33910ms)
[ZP] Exception: __ [RUE] Ответ банка: Неверный статус устройства
[ZP] Call stack:
Error: [RUE] Ответ банка: Неверный статус устройства
    at /data/user/0/ru.zenmoney.androidsub/files/ZenPlugin/alfabank-by/index.js:33:43417
    at y (/data/user/0/ru.zenmoney.androidsub/files/ZenPlugin/alfabank-by/index.js:27:229954)
    at Generator._invoke (/data/user/0/ru.zenmoney.androidsub/files/ZenPlugin/alfabank-by/index.js:27:229742)
    at Generator.e.(anonymous function) [as next] (/data/user/0/ru.zenmoney.androidsub/files/ZenPlugin/alfabank-by/index.js:27:230133)
    at r (/data/user/0/ru.zenmoney.androidsub/files/ZenPlugin/alfabank-by/index.js:33:40721)
    at /data/user/0/ru.zenmoney.androidsub/files/ZenPlugin/alfabank-by/index.js:33:40815
    at /data/user/0/ru.zenmoney.androidsub/files/ZenPlugin/alfabank-by/index.js:27:196900
    at /data/user/0/ru.zenmoney.androidsub/files/ZenPlugin/alfabank-by/index.js:27:196928
    at e.exports (/data/user/0/ru.zenmoney.androidsub/files/ZenPlugin/alfabank-by/index.js:33:17777)
    at /data/user/0/ru.zenmoney.androidsub/files/ZenPlugin/alfabank-by/index.js:27:196800

**Comment by vetheslav** [comment]
@alparo фикс этой проблемы здесь: https://github.com/zenmoney/ZenPlugins/pull/295
В любом случай банк отправляет сообщение: "Мы заблокировали приложение. Вы можете разблокировать его в «Альфа-Клике» (Настройки>Безопасность), в онлайн-чате или контакт-центре".
Разблокируйте и все будет работать.

**Comment by alparo** [comment]
Спасибо. Теперь работает!
