### ISSUE TITLE
[RocketBank] Ошибка подключения синхронизации iOS & Android

### ISSUE THREAD

**Issue by ArtemKosorukov** [zenmoney/ZenPlugins#297]
Код ошибки сначала был [40], теперь [41].
Пытался многократно и многодневно подключить синхронизацию и на iOS и на Android.
Результат одинаковый:

Необходимо привязать устройство...
Отправляем запрос на регистрацию устройства zenmoney_34a8e6c3f8a2057d8a8d0a********** (+79269909***)
Смс с кодом отправлено
Получили код
Подтвержден
Устройство привязано
Загружаем профиль пользователя
Требуется создать новый токен
Пароль получен, отправляем запрос
Не удалось подтвердить телефон: Неправильный логин или пароль
[ZP] Exception: __ Не удалось подтвердить телефон
[ZP] Call stack:
error@main.js:824:33
getToken@main.js:629:22
loadProfile@main.js:278:54
sync@main.js:46:39
main@main.js:9:34

Самое мне не понятное, что товарищ позже меня смог удачно (но не с первой попытки) подключить синхронизацию на iOS.

Need help

**Comment by ArtemKosorukov** [comment]
@afedosin

**Comment by Mamontosik** [comment]
Присоединяюсь, проблема актуальна. При синхронизации выводится ошибка [41]

Лог ошибки:

Загружаем профиль пользователя
Требуется создать новый токен
Пароль получен, отправляем запрос
Не удалось подтвердить телефон: Сессия устарела
[ZP] Exception: __ Не удалось подтвердить телефон
[ZP] Call stack:
error@main.js:824:33
getToken@main.js:629:22
requestProfile@main.js:300:55
loadProfile@main.js:278:37
sync@main.js:46:39
main@main.js:9:34

**Comment by jonny3D** [comment]
Рокетбанк переведён на новое API. Если будут замечания, пожалуйста, пишите.
