### ISSUE TITLE
[Альфабанк Беларусь] По некоторым счетам не добавляются операции

### ISSUE THREAD

**Issue by alparo** [zenmoney/ZenPlugins#300]
Начал пользоваться плагином впервые. После синхронизации появилась корректировка, а транзакцию не увидело, хотя она была в логе.
После переподключения к банку транзакции в логе больше нет, хотя в приложении insync в истории транзакция видна.

Добавил новый счет в insync (без привязанной карты). Отключил и потом снова включил синхронизацию с банком. Плагин не предложил мне завести новый счет в дзен-мани к счету, созданному в insync. У меня создано 4 счета в insync, а плагин, судя по логам, видит только три счета. При этом добавляет в дзен-мани только два из них.

Логи могу прислать, но не знаю на какой адрес лучше слать. Там много чувствительной информации. Могу выслать только то, что дзен-мани выгружает в тело письма, но не запароленный архив. И то только после того, как почищу логи руками.

P.S. часть лога уже отправил на support@zenmoney.ru

**Comment by vetheslav** [comment]
@alparo исправление подгрузки всех аккаунтов должно быть здесь: https://github.com/zenmoney/ZenPlugins/pull/302

**Comment by vetheslav** [comment]
@alparo в логах что Вы отправляли на support@zenmoney.ru, я не могу найти Ваши операции. Вы точно прислали полный лог?

**Comment by skvav** [comment]
Изменения перенес в #304, выложил в прод

**Comment by alparo** [comment]
Один раз синхронизировалось. А теперь выдает ошибку:
TypeError: [RUE] Cannot read property 'amount' of undefined.

@vetheslav написал вам в Телеграм.

**Comment by vetheslav** [comment]
https://github.com/zenmoney/ZenPlugins/pull/305 здесь правка последней проблемы
