### ISSUE TITLE
[alfabank-by] При оплате через ЕРИП брать комментарий из title

### ISSUE THREAD

**Issue by alparo** [zenmoney/ZenPlugins#313]
При оплате по ЕРИП альфабанк пишет постоянно один и тот же текст в поле description. Полезная информация при этом передаётся в поле title. 
Моё предложение:
Если operation: 'PAYMENT', то брать данные для заполнения комментария в дзен-мани из поля 'title' , а не из 'description' .

**Comment by vetheslav** [comment]
@alparo может у Вас есть возможность сбросить пример ответа от банка с такой транзакцией?

**Comment by alparo** [comment]
Такая транзакция уже есть в тестовых случая тут:

name: 'ERIP payment',
      json: {
        id: '11113111050111',
        info:
          {
            description: 'А-курс',
            title: 'MTS - Domashnij internet: 000000000',
            amount: {
              format: '###,###,###,###,##0.##',
              currency: 'BYN',
              amount: -5
            },
            icon:
              {
                backgroundColorFrom: '#6cbfc7',
                backgroundColorTo: '#97f6e6',
                iconUrl: 'v0/Image/49902_392.SVG',
                captionColor: '#FFFFFF',
                frameColor: '#c2b7b7',
                displayType: 'REGULAR'
              }
          },
        date: '20190125122755',
        cardMask: '4.0000',
        description: 'INTERNET-BANK AL InSync (ERIP)',
        status: 'NORMAL',
        operation: 'PAYMENT',
        iban: 'BY31 ALFA 3014 111M RT00 1111 0000',
        showReceipt: true,
        sendReceipt: true,
        showAddToFuture: true,
        showRepeat: true,
        showAddRecipient: true,
        availableSplit: true,
        showCompensate: false
      },
      expectedTransaction: {
        date: new Date('Tue Jan 25 2019 12:27:55 GMT+0300 (Moscow Standard Time)'),
        movements: [
          {
            id: '11113111050111',
            account: { id: '6505111' },
            invoice: null,
            sum: -5,
            fee: 0
          }
        ],
        merchant: null,
        comment: 'MTS - Domashnij internet: 000000000',
        hold: false
      }
    },

**Comment by alparo** [comment]
@vetheslav в тестовых кейсах тут уже есть аналогичная. Добавлю самую свежую, что у меня есть:

` { id: '36148785',
          info: 
           { description: 'Зарплатная',
             **title: 'MTS - Domashnij internet: 000000000',**
             amount: 
              { format: '###,###,###,###,##0.##',
                currency: 'BYN',
                amount: -5 },
             icon: 
              { backgroundColorFrom: '#6cbfc7',
                backgroundColorTo: '#97f6e6',
                iconUrl: 'v0/Image/49902_392.SVG',
                captionColor: '#FFFFFF',
                frameColor: '#c2b7b7',
                displayType: 'REGULAR' } },
          date: '20190517111955',
          cardMask: '4.2815',
          **description: 'Оплата товаров/услуг со счета 3014688214003',**
          status: 'NORMAL',
          **operation: 'PAYMENT',**
          iban: '**** **** **** **** **** **** ****',
          showReceipt: true,
          sendReceipt: true,
          showAddToFuture: true,
          showRepeat: true,
          showAddRecipient: true,
          availableSplit: true,
          showCompensate: false },`

**Comment by vetheslav** [comment]
Фикс здесь https://github.com/zenmoney/ZenPlugins/pull/332

**Comment by alparo** [comment]
Работает. Большое спасибо!
