### ISSUE TITLE
[alfabank-by] При COMPANYTRANSFER использовать также поле title

### ISSUE THREAD

**Issue by alparo** [zenmoney/ZenPlugins#314]
При платеже по реквизитам генерируются две транзакции. Одна - с title='Комиссия', вторая - с title содержащим имя получателя. 
Предлагаю:
Если operation: 'COMPANYTRANSFER', то заполнять место платежа в дзен-мани данными из поля title.
Можно пойти ещё дальше и если (operation: 'COMPANYTRANSFER') AND (title: 'Комиссия'), то место платежа устанавливать как 'Альфабанк'. Но я не знаю принято ли в плагинах так хардкодить...

**Comment by vetheslav** [comment]
@alparo может у Вас есть возможность сбросить пример ответа от банка с такой транзакцией?
Хардкодить конечно можно и нужно, поэтому место платежа установить возможно.

**Comment by alparo** [comment]
Да. Конечно. Вот:

 { id: 'ABOWD00128949486',
          info: 
           { description: 'Зарплатная',
             title: 'Комиссия',
             amount: { format: '###,###,###,###,##0.##', currency: 'BYN', amount: -1 },
             icon: 
              { backgroundColorFrom: '#32cb77',
                backgroundColorTo: '#32cb77',
                iconUrl: 'v0/Image/53_392.SVG',
                captionColor: '#FFFFFF',
                frameColor: '#c2b7b7',
                displayType: 'REGULAR' } },
          date: '20190506164458',
          description: 'Перевод на осн. эл.сообщ. от 06.05.2019 ПУПКИН ИВАН ИВАНОВИЧ Оплата по договору № 1112-2018ЛУ от 13.01.2019г., Пупкин И.И., Платеж №2',
          status: 'NORMAL',
          operation: 'COMPANYTRANSFER',
          iban: '**** **** **** **** **** **** ****',
          showReceipt: true,
          sendReceipt: true,
          showAddToFuture: true,
          showRepeat: true,
          showAddRecipient: true,
          availableSplit: false,
          showCompensate: false },
        { id: 'ABOWD00128949486',
          info: 
           { description: 'Зарплатная',
             title: 'ООО "Рога и Копыта"',
             amount: 
              { format: '###,###,###,###,##0.##',
                currency: 'BYN',
                amount: -300.4 },
             icon: 
              { backgroundColorFrom: '#32cb77',
                backgroundColorTo: '#32cb77',
                iconUrl: 'v0/Image/53_392.SVG',
                captionColor: '#FFFFFF',
                frameColor: '#c2b7b7',
                displayType: 'REGULAR' } },
          date: '20190506164458',
          description: 'Перевод на осн. эл.сообщ. от 06.05.2019 ПУПКИН ИВАН ИВАНОВИЧ Оплата по договору № 1112-2018ЛУ от 13.01.2019г., Пупкин И.И., Платеж №2',
          status: 'NORMAL',
          operation: 'COMPANYTRANSFER',
          iban: '**** **** **** **** **** **** ****',
          showReceipt: true,
          sendReceipt: true,
          showAddToFuture: true,
          showRepeat: true,
          showAddRecipient: true,
          availableSplit: false,
          showCompensate: false },

**Comment by vetheslav** [comment]
Фикс здесь https://github.com/zenmoney/ZenPlugins/pull/332

**Comment by alparo** [comment]
Операции с operation: 'COMPANYTRANSFER' на данный момент вообще не распознаются. :(
