### ISSUE TITLE
Обновление документации на wiki

### ISSUE THREAD

**Issue by Felixoid** [zenmoney/ZenPlugins#321]
Доброго вечера.

Я поправил страницу wiki для ZenMoney API, но не знаю, как можно отправить PR на это изменение.
https://github.com/Felixoid/ZenPlugins/wiki/ZenMoney-API

Причесал описания параметров, сделал их консистентными, добавил переносы строк и TOC.

Как можно забрать изменения командной строкой:

```bash
git clone git@github.com:zenmoney/ZenPlugins.wiki.git
cd ZenPlugins.wiki
git remote add felixoid git@github.com:Felixoid/ZenPlugins.wiki.git
git fetch felixoid
git merge felixoid/master
git push origin
```

**Comment by Felixoid** [comment]
Господа разработчики?

**Comment by skvav** [comment]
Спасибо! Выложили
