### ISSUE TITLE
[Rocketbank] Подключение к банку не работает 

### ISSUE THREAD

**Issue by Mamontosik** [zenmoney/ZenPlugins#324]
В момент авторизации по присланному от банка коду выводится ошибка [41]

Log:
Необходимо привязать устройство...
Отправляем запрос на регистрацию устройства zenmoney_dc25c795f81f05d82421e9********** (+7916***)
Смс с кодом отправлено
Получили код
Подтвержден
[ZP] Exception: __ undefined is not an object (evaluating 'data.user.email')
[ZP] Call stack:
verifyDevice@main.js:688:44
registerDevice@main.js:657:21
getDevice@main.js:591:38
loadProfile@main.js:276:31
sync@main.js:46:39
main@main.js:9:34
global code

**Comment by Mamontosik** [comment]
А какой статус у этой доработки?

**Comment by jonny3D** [comment]
> А какой статус у этой доработки?

В процессе 🙂
Напишите нам в чате приложения свой логин, пожалуйста, чтобы мы добавили вас в число первых бета-тестеров.

**Comment by Mamontosik** [comment]
Готово. Написал.

**Comment by jonny3D** [comment]
Исправлено. Если есть замечания, дополните 🙂
