### ISSUE TITLE
Объект budget не вернул аттрибут id

### ISSUE THREAD

**Issue by Felixoid** [zenmoney/ZenPlugins#341]
Приветствую. В документации указано, что [budget](https://github.com/zenmoney/ZenPlugins/wiki/ZenMoney-API#budget) должен содержать обязательный аттрибут id. Апи же его не возвращает:

```
In [50]: api.diff({'currentClientTimestamp': 10})['budget']                                                           
Out[50]: 
[{'user': 377742,
  'changed': -52138060,
  'date': '2017-10-01',
  'tag': '00000000-0000-0000-0000-000000000000',
  'income': 0,
  'outcome': 0,
  'incomeLock': False,
  'outcomeLock': False}]
```

Это ошибка в API или в документации?

**Comment by skvav** [comment]
Да, была ошибка в документации. Спасибо за правку!
