### ISSUE TITLE
Ошибки в работе с Беларусбанком

### ISSUE THREAD

**Issue by YuraFilionchik** [zenmoney/ZenPlugins#344]
Столкнулся с проблемами в работе программы с АСБ Беларусбанк:
1. Незначительная. Не отправляется лог подключения (точнее ~1 раз из 20 попыток).
2. Критическая. Неверно считывает с сайта текущий баланс. На счете имеется подключенный овердрафт, программа только его считывает и считает баланс счёта всегда равными размеру овердрафта. 
Может ли кто поправить?

**Comment by vetheslav** [comment]
@YuraFilionchik можете выслать лог синхронизации в support?

**Comment by YuraFilionchik** [comment]
Я высылал несколько раз, сказали что ничего полезного, мусор. Я заметил, что если подключение и синхронизация успешные, то лог не генерируется и соответственно нажатие на кнопку отправление логов ничего не даёт, реакции нет. Пятница, 05 июля 2019г., 19:28 +03:00 от Slava Shahoika  notifications@github.com :

**Comment by vetheslav** [comment]
> Я высылал несколько раз, сказали что ничего полезного, мусор. Я заметил, что если подключение и синхронизация успешные, то лог не генерируется и соответственно нажатие на кнопку отправление логов ничего не даёт, реакции нет. Пятница, 05 июля 2019г., 19:28 +03:00 от Slava Shahoika notifications@github.com :
> […](#)
> @YuraFilionchik можете выслать лог синхронизации в support? — You are receiving this because you were mentioned. Reply to this email directly, view it on GitHub , or mute the thread .

Можете связаться со мной в telegram? Данные есть в github аккаунте

**Comment by mckrasnov** [comment]
Лог отправил, теперь проблема другая..) Если раньше синхронизация была, но счет обнулялся, то сейчас вылезает ошибка. 
![Ошибка Беларусбанк](https://user-images.githubusercontent.com/52564443/61167876-7c6b9180-a54d-11e9-9f78-625591e122f4.jpg)
