### ISSUE TITLE
[alfabank-by] Синхронизация транзакций депозита

### ISSUE THREAD

**Issue by VladMomotov** [zenmoney/ZenPlugins#350]
Вот такая ошибка при синхронихации вылетает
![download](https://user-images.githubusercontent.com/17363319/60742829-8e5e9a80-9f77-11e9-8d7b-a5a9447ad7d5.png)

Как я понял, это из-за того что `iban` транзакции в сокращенном формате и не совпадает с `syncID[0]` аккаунта
![download](https://user-images.githubusercontent.com/17363319/60742907-da114400-9f77-11e9-8b6d-9efa773536b3.png)
![download](https://user-images.githubusercontent.com/17363319/60742936-04630180-9f78-11e9-9434-428fe7b4f6ff.png)

**Comment by vetheslav** [comment]
@VladMomotov Ваша проблема до сих пор актуальна?

**Comment by VladMomotov** [comment]
@vetheslav уже нет :)
