### ISSUE TITLE
[Альфабанк Беларусь] Не загружаются транзакции, после каждой синхоринизации просто создается корректировка баланса

### ISSUE THREAD

**Issue by georgeeeeb** [zenmoney/ZenPlugins#360]

**Comment by AntonRutkevich** [comment]
Подтверждаю, не может сопоставить ни одну транзакцию со счетом, вываливает все на один, видимо по умолчанию.

**Comment by georgeeeeb** [comment]
Fixed

**Comment by georgeeeeb** [comment]
Баг вернулся после обновления

**Comment by vetheslav** [comment]
Предлагаю объединить с https://github.com/zenmoney/ZenPlugins/issues/372

**Comment by vetheslav** [comment]
@georgeeeeb Вы можете связаться со мной через Телеграмм, для того чтоб посмотреть на эту проблему вместе? Уверен что у вас специфический кейс, который нужно просто специально обработать
