### ISSUE TITLE
Проблема при подключении к Белинвестбанку

### ISSUE THREAD

**Issue by palvikt** [zenmoney/ZenPlugins#370]
Программа предлагает ввести логин и пароль от банкинга. После ввода СМС от банкинга выдает ошибку
![Screenshot_2019-08-29-18-47-00-894_ru zenmoney androidsub](https://user-images.githubusercontent.com/54678604/63955500-772abd80-ca8d-11e9-9c39-e1d3df150b9b.png)

**Comment by vetheslav** [comment]
@palvikt к сожалению сложно по этому логу понять где именно ошибка, нужно Ваше участие. Можете мне написать в телегу?

**Comment by palvikt** [comment]
Согласен, что сложно.) Телеги у меня нет. Лог прилагаю сюда. Пароль 06z2wispy8u0j9oj9vyniwq4ekt33l8p. Я еще и на support письмо отправлял 29.08.2019 с ящика pal.vikt.p@gmail.com
[log_2019-08-29-14-33-26.zip](https://github.com/zenmoney/ZenPlugins/files/3580975/log_2019-08-29-14-33-26.zip)

**Comment by vetheslav** [comment]
@palvikt Я видел Ваш лог ранее, но спасибо. Написал Вам на почту

**Comment by vetheslav** [comment]
@palvikt Решение Вашей проблемы здесь: https://github.com/zenmoney/ZenPlugins/pull/380
