### ISSUE TITLE
[alfabank-by] При переводе с карты на карту создаются две транзакции через наличный кошелек

### ISSUE THREAD

**Issue by alparo** [zenmoney/ZenPlugins#374]
При переводе с "карта USD" на "карта BYN" создаются две транзакции:
"карта USD" -> "Кошелек BYN"
"Кошелек BYN" -> "карта BYN"

А должна создаваться только одна транзакция "карта USD" -> "карта BYN"

Похоже, это связано с изменением API дзен-мани. Нужно переписывать плагин.

**Comment by alparo** [comment]
Такая же проблема, кстати, и у МТБанка.

**Comment by skvav** [comment]
Синхронизация с Альфа-Банком временно приостановлена, банк разрабатывает официальное открытое API, ждем их.

**Comment by skvav** [comment]
Касательно МТБанка, пожалуйста пришлите лог дополненный описанием ошибки, и какие именно операции не так были обработаны.
