### ISSUE TITLE
[alfabank-by] Не подтягивается "Место платежа"

### ISSUE THREAD

**Issue by OdNairy** [zenmoney/ZenPlugins#392]
Транзакции из США практически никогда не выставляют "Место платежа", хотя корректная информация в интернет-банкинге присутствует. Вместо этого выставляется информация из поля "Дополнительная информация".  

![IMG_2479](https://user-images.githubusercontent.com/735178/65844102-d5ec8c80-e302-11e9-9150-711b9301fc10.jpeg)

![IMG_2480](https://user-images.githubusercontent.com/735178/65844311-bb66e300-e303-11e9-9d7f-777546336e6f.png)

**Comment by vetheslav** [comment]
@OdNairy вышлите Ваш лог с указанием этого PR, пожалуйста. Обязательно что-нибудь придумаем в будущих версиях

**Comment by OdNairy** [comment]
Отправлено

**Comment by vetheslav** [comment]
@OdNairy обработал пару Ваших кейсов: https://github.com/zenmoney/ZenPlugins/pull/408

**Comment by OdNairy** [comment]
После чистого перезапуска все места определились верно. Спасибо
