### ISSUE TITLE
Не работает первоначальная синхронизация с Русским Стандартом

### ISSUE THREAD

**Issue by MaxNadeev** [zenmoney/ZenPlugins#411]
В отчете Ошибка с заголовком "идет загрузка" и почему то на одной из строк вижу, что название плагина russtandart, но такого не вижу плагина вообще на Github Что за странная магия? И как сделать, чтоб Русский Стандарт синхронизировался?

**Comment by skvav** [comment]
В открытом доступе лежат плагины, которые разрабатываются с помощью сообщества и не требуют дополнительных договоренностей с банками.
Выкатили правки по Русскому Стандарту, попробуйте, пожалуйста, еще раз.

**Comment by MaxNadeev** [comment]
Да, это заработало! Спасибо автору. Насколько понял, там из-за смс авторизации была проблема?



Sent from Mail.ru app for iOS


Friday, 25 October 2019, 14:05 +0300 from notifications@github.com  <notifications@github.com>:
