### ISSUE TITLE
[mtbank] ошибка входа

### ISSUE THREAD

**Issue by GhoulJedi** [zenmoney/ZenPlugins#431]
Не происходит подключение. В отчете, который отправлял через приложение, есть такой кусок`[log] call anonymous with args: { preferences: { phone: '<string[12]>', password: '<string[14]>' },
  fromDate: Thu Oct 17 2019 00:00:00 GMT+0300 (+03),
  toDate: null,
  isFirstRun: true }
[debug] request { method: 'POST',
  url: 'https://mybank.by/api/v1/login/userIdentityByPhone',
  headers: 
  { Accept: 'application/json, text/plain, */*',
    'Content-Type': 'application/json;charset=UTF-8' },
  body: { phoneNumber: '<string[12]>', loginWay: '1' } }
[debug] response { status: 200,
  url: 'https://mybank.by/api/v1/login/userIdentityByPhone',
  headers: 
  { 'content-type': 'application/json;charset=UTF-8',
    'x-content-security-policy': 'default-src \'self\' ; frame-src  \'self\' https://api.mtbank.by https://mpi.mtbank.by https://mpi.mtbank.by:80  https://acs.mtbank.by https://c2c.mtbank.by https://3ds.alfabank.by https://3ds.priorbank.by https://acs.bgpb.by https://sca.npc.by https://www.sbs4u.by https://acs.multicarta.ru https://aacsw.3ds.verifiedbyvisa.com https://cap.attempts.securecode.com https://ipcacs.sberbank.ru; script-src \'self\' \'unsafe-inline\' \'unsafe-eval\' https://app.blinger.io https://static.mybank.by https://api.mtbank.by https://www.google-analytics.com  https://halva.mtbank.by https://www.googletagmanager.com https://tagmanager.google.com; style-src \'self\' blob: \'unsafe-inline\' https://static.mybank.by;img-src \'self\' https://blinger.io  https://app.blinger.io https://static.mybank.by data: blob:  https://www.google-analytics.com  https://www.googletagmanager.com ; font-src \'self\' https://static.mybank.by; connect-src \'self\' wss://app.blinger.io; media-src \'self\'',
    'content-security-policy': 'default-src \'self\' ; frame-src  \'self\' https://api.mtbank.by https://mpi.mtbank.by https://mpi.mtbank.by:80  https://acs.mtbank.by https://c2c.mtbank.by https://3ds.alfabank.by https://3ds.priorbank.by https://acs.bgpb.by https://sca.npc.by https://www.sbs4u.by https://acs.multicarta.ru https://aacsw.3ds.verifiedbyvisa.com https://cap.attempts.securecode.com https://ipcacs.sberbank.ru; script-src \'self\' \'unsafe-inline\' \'unsafe-eval\' https://app.blinger.io  https://static.mybank.by https://api.mtbank.by https://www.google-analytics.com  https://halva.mtbank.by https://www.googletagmanager.com  https://tagmanager.google.com; style-src \'self\' blob: \'unsafe-inline\' https://static.mybank.by;img-src \'self\' https://blinger.io  https://app.blinger.io  https://static.mybank.by data: blob:  https://www.google-analytics.com  https://www.googletagmanager.com ; font-src \'self\' https://static.mybank.by; connect-src \'self\' wss://app.blinger.io; media-src \'self\'',
    'set-cookie': '<string[371]>',
    'content-encoding': 'gzip',
    'x-xss-protection': '1; mode=block',
    'transfer-encoding': 'Identity',
    'referrer-policy': 'strict-origin',
    date: 'Fri, 18 Oct 2019 14:46:15 GMT',
    'strict-transport-security': 'max-age=16070400; includeSubDomains',
    'x-content-type-options': 'nosniff',
    'x-oneagent-js-injection': 'true',
    'x-frame-options': 'SAMEORIGIN',
    vary: 'Accept-Encoding' },
  body: 
  { ResponseType: 'ResponseOfUserIdentityByPhoneData',
    error: null,
    sessionId: null,
    success: true,
    validateErrors: null,
    data: { smsCode: null, userLinkedAbs: true } },
  ms: 289 }
[debug] request { method: 'POST',
  url: 'https://mybank.by/api/v1/login/checkPassword2',
  headers: 
  { Accept: 'application/json, text/plain, */*',
    'Content-Type': 'application/json;charset=UTF-8',
    Cookie: '<string[230]>' },
  body: { password: '<string[14]>', version: '2.1.4' } }
[debug] response { status: 410,
  url: 'https://mybank.by/api/v1/login/checkPassword2',
  headers: 
  { 'content-type': 'application/json;charset=UTF-8',
    'x-content-security-policy': 'default-src \'self\' ; frame-src  \'self\' https://api.mtbank.by https://mpi.mtbank.by https://mpi.mtbank.by:80  https://acs.mtbank.by https://c2c.mtbank.by https://3ds.alfabank.by https://3ds.priorbank.by https://acs.bgpb.by https://sca.npc.by https://www.sbs4u.by https://acs.multicarta.ru https://aacsw.3ds.verifiedbyvisa.com https://cap.attempts.securecode.com https://ipcacs.sberbank.ru; script-src \'self\' \'unsafe-inline\' \'unsafe-eval\' https://app.blinger.io https://static.mybank.by https://api.mtbank.by https://www.google-analytics.com  https://halva.mtbank.by https://www.googletagmanager.com https://tagmanager.google.com; style-src \'self\' blob: \'unsafe-inline\' https://static.mybank.by;img-src \'self\' https://blinger.io  https://app.blinger.io https://static.mybank.by data: blob:  https://www.google-analytics.com  https://www.googletagmanager.com ; font-src \'self\' https://static.mybank.by; connect-src \'self\' wss://app.blinger.io; media-src \'self\'',
    'content-security-policy': 'default-src \'self\' ; frame-src  \'self\' https://api.mtbank.by https://mpi.mtbank.by https://mpi.mtbank.by:80  https://acs.mtbank.by https://c2c.mtbank.by https://3ds.alfabank.by https://3ds.priorbank.by https://acs.bgpb.by https://sca.npc.by https://www.sbs4u.by https://acs.multicarta.ru https://aacsw.3ds.verifiedbyvisa.com https://cap.attempts.securecode.com https://ipcacs.sberbank.ru; script-src \'self\' \'unsafe-inline\' \'unsafe-eval\' https://app.blinger.io  https://static.mybank.by https://api.mtbank.by https://www.google-analytics.com  https://halva.mtbank.by https://www.googletagmanager.com  https://tagmanager.google.com; style-src \'self\' blob: \'unsafe-inline\' https://static.mybank.by;img-src \'self\' https://blinger.io  https://app.blinger.io  https://static.mybank.by data: blob:  https://www.google-analytics.com  https://www.googletagmanager.com ; font-src \'self\' https://static.mybank.by; connect-src \'self\' wss://app.blinger.io; media-src \'self\'',
    'set-cookie': '<string[364]>',
    'content-encoding': 'gzip',
    'x-xss-protection': '1; mode=block',
    'transfer-encoding': 'Identity',
    'referrer-policy': 'strict-origin',
    date: 'Fri, 18 Oct 2019 14:46:16 GMT',
    'strict-transport-security': 'max-age=16070400; includeSubDomains',
    'x-content-type-options': 'nosniff',
    'x-oneagent-js-injection': 'true',
    'x-frame-options': 'SAMEORIGIN',
    vary: 'Accept-Encoding' },
  body: 
  { success: false,
    data: null,
    error: 
      { code: 'UNSUPPORTED_VERSION',
        description: 'Установите новую версию приложения',
        lockedTime: null,
        errorType: null,
        discriminator: null,
        error_description: 'Установите новую версию приложения' },
    validateErrors: null,
    sessionId: null },
  ms: 70 }
[error] anonymous call rejected with [Error: Assertion failed: non-successful response] 
(377ms)
[ZP] Exception: __ [RUE] Assertion failed: non-successful response
[ZP] Call stack:
assert@index.js:1:563763
h@index.js:1:570006
file:///var/mobile/Containers/Data/Application/31AE0F96-D0A1-4976-A9A3-0B448675EE9B/Library/ZenPlugin/mtbank/index.js:1:568814
y@index.js:1:525122
file:///var/mobile/Containers/Data/Application/31AE0F96-D0A1-4976-A9A3-0B448675EE9B/Library/ZenPlugin/mtbank/index.js:1:524907
r@index.js:1:569693
file:///var/mobile/Containers/Data/Application/31AE0F96-D0A1-4976-A9A3-0B448675EE9B/Library/ZenPlugin/mtbank/index.js:1:569788
file:///var/mobile/Containers/Data/Application/31AE0F96-D0A1-4976-A9A3-0B448675EE9B/Library/ZenPlugin/mtbank/index.js:1:492065
file:///var/mobile/Containers/Data/Application/31AE0F96-D0A1-4976-A9A3-0B448675EE9B/Library/ZenPlugin/mtbank/index.js:1:492092
file:///var/mobile/Containers/Data/Application/31AE0F96-D0A1-4976-A9A3-0B448675EE9B/Library/ZenPlugin/mtbank/index.js:1:545051
file:///var/mobile/Containers/Data/Application/31AE0F96-D0A1-4976-A9A3-0B448675EE9B/Library/ZenPlugin/mtbank/index.js:1:491965
u@index.js:1:492193
file:///var/mobile/Containers/Data/Application/31AE0F96-D0A1-4976-A9A3-0B448675EE9B/Library/ZenPlugin/mtbank/index.js:1:493268
file:///var/mobile/Containers/Data/Application/31AE0F96-D0A1-4976-A9A3-0B448675EE9B/Library/ZenPlugin/mtbank/index.js:1:492911
f@index.js:1:492940
a@index.js:1:491769
file:///var/mobile/Containers/Data/Application/31AE0F96-D0A1-4976-A9A3-0B448675EE9B/Library/ZenPlugin/mtbank/index.js:1:569641
y@index.js:1:525122
file:///var/mobile/Containers/Data/Application/31AE0F96-D0A1-4976-A9A3-0B448675EE9B/Library/ZenPlugin/mtbank/index.js:1:524907
r@index.js:1:569693
file:///var/mobile/Containers/Data/Application/31AE0F96-D0A1-4976-A9A3-0B448675EE9B/Library/ZenPlugin/mtbank/index.js:1:569788
file:///var/mobile/Containers/Data/Application/31AE0F96-D0A1-4976-A9A3-0B448675EE9B/Library/ZenPlugin/mtbank/index.js:1:492065
file:///var/mobile/Containers/Data/Application/31AE0F96-D0A1-4976-A9A3-0B448675EE9B/Library/ZenPlugin/mtbank/index.js:1:492092
file:///var/mobile/Containers/Data/Application/31AE0F96-D0A1-4976-A9A3-0B448675EE9B/Library/ZenPlugin/mtbank/index.js:1:545051
file:///var/mobile/Containers/Data/Application/31AE0F96-D0A1-4976-A9A3-0B448675EE9B/Library/ZenPlugin/mtbank/index.js:1:491965
u@index.js:1:492193
file:///var/mobile/Containers/Data/Application/31AE0F96-D0A1-4976-A9A3-0B448675EE9B/Library/ZenPlugin/mtbank/index.js:1:493268
file:///var/mobile/Containers/Data/Application/31AE0F96-D0A1-4976-A9A3-0B448675EE9B/Library/ZenPlugin/mtbank/index.js:1:492911
f@index.js:1:492940
a@index.js:1:491769
file:///var/mobile/Containers/Data/Application/31AE0F96-D0A1-4976-A9A3-0B448675EE9B/Library/ZenPlugin/mtbank/index.js:1:569641
y@index.js:1:525122
file:///var/mobile/Containers/Data/Application/31AE0F96-D0A1-4976-A9A3-0B448675EE9B/Library/ZenPlugin/mtbank/index.js:1:524907
r@index.js:1:576901
file:///var/mobile/Containers/Data/Application/31AE0F96-D0A1-4976-A9A3-0B448675EE9B/Library/ZenPlugin/mtbank/index.js:1:492911
f@index.js:1:492940
a@index.js:1:491769
file:///var/mobile/Containers/Data/Application/31AE0F96-D0A1-4976-A9A3-0B448675EE9B/Library/ZenPlugin/mtbank/index.js:1:576849
file:///var/mobile/Containers/Data/Application/31AE0F96-D0A1-4976-A9A3-0B448675EE9B/Library/ZenPlugin/mtbank/index.js:1:549972
file:///var/mobile/Containers/Data/Application/31AE0F96-D0A1-4976-A9A3-0B448675EE9B/Library/ZenPlugin/mtbank/index.js:1:547081
file:///var/mobile/Containers/Data/Application/31AE0F96-D0A1-4976-A9A3-0B448675EE9B/Library/ZenPlugin/mtbank/index.js:1:549097
global code`

**Comment by vetheslav** [comment]
@GhoulJedi исправление здесь: https://github.com/zenmoney/ZenPlugins/pull/433
