### ISSUE TITLE
Ошибка синхронизации с Рокетбанком

### ISSUE THREAD

**Issue by 4epexa** [zenmoney/ZenPlugins#446]
После последнего обновления от Рокетбанка сломалась синхронизация с Рокетбанком.

Логи ошибки высылал Вам с адреса 4epexa@gmail.com

**Comment by tribals** [comment]
Оказывается, и плагин уже удалён, но, видимо, релиза приложения ещё не было. Так что в приложении Рокетбанк всё ещё доступен для поключения синхронизации, однако она не работает :disappointed:

**Comment by Mamontosik** [comment]
Решено
