### ISSUE TITLE
[belgazprombank] Операции оплаты ЕРИП добавляются без комментария

### ISSUE THREAD

**Issue by alparo** [zenmoney/ZenPlugins#447]
Операции оплаты ЕРИП добавляются без комментария. Невозможно определить за что именно был тот или иной платеж.
В логах я не смог найти нужной информации. Но она видна в истории операций в мобильном приложении. Возможно, можно сделать еще какой-то запрос чтобы получить развернутую выписку и выдрать из нее комментарии?

**Comment by vetheslav** [comment]
@alparo возможно, а не могли бы Вы выслать лог на почту с синхронизацией? Возможно что-нибудь придумаем

**Comment by alparo** [comment]
> @alparo возможно, а не могли бы Вы выслать лог на почту с синхронизацией? Возможно что-нибудь придумаем

отправил на почту лог.
Я также написал в банк просьбу добавлять более подробную информацию в пуши. Пуши в логе видны, надеюсь, они быстро реализуют и это поможет.

**Comment by vetheslav** [comment]
@alparo добавили информацию в пуши?

**Comment by alparo** [comment]
> @alparo добавили информацию в пуши?

к сожалению, до сих пор нет. Если тикет мешает, то  можем его закрыть и я открою новый, когда/если информация все-таки в пушах начнет появляться.

**Comment by skvav** [comment]
@alparo Если до сих пор не работает, то создайте новый тикет, пожалуйста.
