### ISSUE TITLE
[УкрСибБанк] Не работает синхронизация

### ISSUE THREAD

**Issue by alexkutsan** [zenmoney/ZenPlugins#453]
С 14 нября 2019 года не работает синхронизация с УкрСибБанком. 
Нововведение приложении банка - запрашивает код авторизации который приходит в пуш уведомлении. 
После того как в ручную вошел в приложение банка, подтверждение снова не запрашивает, но и не синхронизирует . Пишет Ошибка синхронизации.

**Comment by alexkutsan** [comment]
Сюда кто-то заглядывает?

**Comment by skvav** [comment]
Внесли правки, все еще не работает?

**Comment by alexkutsan** [comment]
@skvav  Работает, огромное спасибо! Какой канал лучше использовать для обратной связи и отслеживания реакции на неё?

**Comment by skvav** [comment]
Да в принципе любой. Нам удобней всего обрабатывать присланные на email логи синхронизации из приложения, с приписанным для ясности комментарием, что не так работает. Их можно отправить прямо из настроек подключения к банку в приложении.
