### ISSUE TITLE
Цели тинькофф, корректировка.

### ISSUE THREAD

**Issue by gost1k** [zenmoney/ZenPlugins#458]
Здравствуйте, 
При создании цели в тинькофф и если на эту цель положить денег, она корректно отображается  и спрашивает создать ли новый счет. И внутри сумма отображается нормально, но при каждой синхронизации с банком, на эту сумму добавляется в ленту запись "корректировка", что очень сильно портит статистику и просто мешает. Можете проверить и поправить?

**Comment by skvav** [comment]
Добрый день! Если проблема еще актуальна, то пришлите лог синхронизации, поправим
