### ISSUE TITLE
Синхронизация с Альфа банком | Ошибка [91]

### ISSUE THREAD

**Issue by vladzh** [zenmoney/ZenPlugins#461]
Добрый
Отвалилась синхронизация с альфабанкам. При синхронизации запрашивает код из смс Потом ошибка 91. К сожалению удалил синхранизацию, пытался создать новую. Лога нет.
![2019-12-24 09-37-32](https://user-images.githubusercontent.com/739254/71398638-1cb3ff00-2632-11ea-8596-93a1b742e0ed.PNG)

**Comment by vladzh** [comment]
При этом Альфа Банк продолжает нормально работать никаких ошибок не выдавая

**Comment by skvav** [comment]
Добрый день! Спасибо за сообщение о баге. С тех пор много правок вносили. Должно работать. Если до сих пор не работает, пожалуйста, сообщите еще раз.
