### ISSUE TITLE
[УкрСибБанк] Не работает подключение банка через приложение

### ISSUE THREAD

**Issue by Rybue** [zenmoney/ZenPlugins#466]
При попытке подключить счет УкрСибБанка, приложение отдает ошибку "object error 37"
Двухфакторная авторизация отключена. В приложение банка захожу без проблем(одноразовый пароль тоже отлючен).

Отправил сообщение и лог ошибки через приложение.

**Comment by skvav** [comment]
Спасибо, поправили, должно работать :)
