### ISSUE TITLE
[Укрсиббанк] Оплата через Apple Pay, ошибки в данных

### ISSUE THREAD

**Issue by rtyshyk** [zenmoney/ZenPlugins#468]
Если оплата сделана через ApplePay, вместо плательщик, пишет "Apple Pay ****1111." где 1111, это 4 последние цифры.  Так же отсутствует комментарий. 

В приложении банка эта информация отображается верно, так что подозреваю API возвращает другие данные для таких транзакций.

Хотел сам посмотреть, но не нашел плагина для Укрсиббанк. Не подскажите как быть :)?

**Comment by tishb** [comment]
ok

**Comment by skvav** [comment]
Спасибо, поправили.
