### ISSUE TITLE
[belgazprombank] Вместо операций добавляются корректировки

### ISSUE THREAD

**Issue by deplodog** [zenmoney/ZenPlugins#473]
Не могу настроить синхронизацию с bgpb. Все операции подгружаются в виде корректировок.

**Comment by vetheslav** [comment]
> Не могу настроить синхронизацию с bgpb. Все операции подгружаются в виде корректировок.

Вы не могли бы переслать лог синхронизации, нажав на кнопку "переслать лог разработчикам"? К сожалению не удается воспроизвести проблемы.

**Comment by deplodog** [comment]
> > Не могу настроить синхронизацию с bgpb. Все операции подгружаются в виде корректировок.
> 
> Вы не могли бы переслать лог синхронизации, нажав на кнопку "переслать лог разработчикам"? К сожалению не удается воспроизвести проблемы.

Приложение вылетает каждый раз, когда я жму на «переслать лог»

**Comment by deplodog** [comment]
Удалось отправить лог с андроид-девайса.

**Comment by vetheslav** [comment]
@deplodog Спасибо за предоставленный лог. В Вашем случае банк отдает только проведенные/подтвержденные банком операции. Когда Вы делаете покупку, эта операция банком по факту еще не проводится, а только блокируется на Вашей карточке.
По этой причине плагин для Белгазпромбанка парсит лог push уведомлений и забирает от туда последние транзакции. Судя по всему они у Вас выключены, поэтому все последние операции приходят корректировками.
Для включения push уведомлений, зайдите во все карточки/счета, выберите "Настройка информирования", и включите push уведомления о новых операциях. На сегодняшний день эта услуга бесплатная, как и во всех других банках.

**Comment by deplodog** [comment]
Спасибо за пояснения
