### ISSUE TITLE
[Сбербанк] Ввод неправильного пароля при подключении меняет пароль в приложении "Сбербанк".

### ISSUE THREAD

**Issue by Sodapoppinc** [zenmoney/ZenPlugins#475]
Если юзер вводит неправильный пароль от своего аккаунта, но подтвердит коды из СМС, то введеный пароль станет новым паролем для его приложения "Сбербанк", и так же, соответственно, запретит вход в него по Touch ID и т.п.

**Comment by isaac-weisberg** [comment]
https://github.com/zenmoney/ZenPlugins/blob/4d0a4b5e8281d3f9c64af653ef15a12486774fcf/src/plugins/sberbank-online/api.js#L133

**Comment by skvav** [comment]
Да, это особенность подключения к Сбербанку. По-другому оно не работает.
