### ISSUE TITLE
[Сбербанк] Ошибка "movement.sum must be Number: ..."

### ISSUE THREAD

**Issue by Sodapoppinc** [zenmoney/ZenPlugins#477]
Ошибка возникла в ситуации, когда пользователь оставил заявку на досрочное погашения кредита с N суммой, и затем успешно погасил кредит.
Предположительно, проблема заключается в том, что, в самом приложении Сбербанк заявка на погашение отображается как операция с N суммой, но в том поле JSON'a, из которого берутся данные - висит null.
![image](https://user-images.githubusercontent.com/52465521/74672764-fdaf9480-51be-11ea-817d-8502752804dc.png)

**Comment by skvav** [comment]
К сожалению, по одному только скриншоту в проблеме не разобраться, нужен лог. Если есть возможность сделать синхронизацию за эти числа и прислать лог, то поправим.
