### ISSUE TITLE
[privatbank] Сихронизация работает раза с 10го

### ISSUE THREAD

**Issue by f0rtis** [zenmoney/ZenPlugins#478]
Синхронизация последние несколько месяцев работает только вручную. И почти всегда выдаёт ошибку "Информация из ПриватБанка временно недоступна. Запустите синхронизацию через некоторое время. Если ситуация повторится, выберите другой IP-адрес в настройках синхронизации с банком." Но после 8-10 попыток синхронизация таки проходит.
При смене IP синхронизация оживает, примерно на день. Потом опять эта ошибка появляется.
Лог, увы, прикрепить не могу, т.к. функция перестала работать.

**Comment by skvav** [comment]
Спасибо за сообщение об ошибке. Добавили возможность синхронизации через апи мобильного приложения Приват24. Должно работать быстрей чем через мерчант, и к тому же такой вариант поддерживает копилки и валютные счета.
