### ISSUE TITLE
[Росбанк] Не считывается sms сообщения Росбанка 

### ISSUE THREAD

**Issue by Mamontosik** [zenmoney/ZenPlugins#481]
Bank: (specify the name of the bank)
SMS text: Karta***** MAGAZIN FASOL 182.20 RUB. Ostatok ****.70 RUB v tom chisle kreditny limit ******.00

System info: 15444, 15444, 15444, 3, 15444, 15444, 3, 15444, 15444, 15444, 4780, 4780

**Comment by skvav** [comment]
Про ошибки распознавания смс лучше писать на support@zenmoney.ru. Это репозиторий про прямые подключения к банкам через плагины.
