### ISSUE TITLE
[belgazprombank] Сессия истекла. Повторите синхронизацию

### ISSUE THREAD

**Issue by alparo** [zenmoney/ZenPlugins#483]
И не синхронизируется. Началось где-то в пятницу.
Отключил синхронизацию и попробовал подключить заново. Не помогло. Зато теперь даже не могу достать логи подключения.

**Comment by vetheslav** [comment]
Привет, здесь фикс: https://github.com/zenmoney/ZenPlugins/pull/484

**Comment by alparo** [comment]
Большое спасибо!
Работает
