### ISSUE TITLE
сихронизация тинькофф банк с использованием номеров других стран.

### ISSUE THREAD

**Issue by S1AnGeR** [zenmoney/ZenPlugins#485]
С недавнего времени в вашем приложении нельзя произвести авторизацию по логину. По телефону тоже не получается, так как у вас стоит проверка на формат, а у меня номер с кодом 
+380

Добавьте, пожалуйста, возможность введения номера в международных форматах. Например
+380941234567

**Comment by skvav** [comment]
Спасибо. Поправили, должно работать
