### ISSUE TITLE
Расширение горизонта планирования на графике в веб-версии

### ISSUE THREAD

**Issue by navff** [zenmoney/ZenPlugins#488]
Доброе утро! Расширьте, пожалуйста, горизонт планирования на графике главной страницы веб-версии. Можно прошлые операции показывать на неделю назад, а вот чем больше видно будущее, — тем лучше. https://i.imgur.com/uzAbXtg.png

Сейчас видно на 1 месяц вперёд, а нужно хотя бы на 3 месяца. 

Я так понимаю, вам нужно один запрос попроавить. Вместо 
https://zenmoney.ru/api/a1/day/?date%5B%5D=2020-03-02&date%5B%5D=2020-05-01
вызывать этот же запрос в веб-клиенте, но с другими датами. Дело не сложное, а счастья даст много.

**Comment by skvav** [comment]
Предложения по веб-версии лучше писать тут https://support.zenmoney.ru/
Но пока все равно работа над веб-версией заморожена.
