### ISSUE TITLE
[Альфа-банк]  ошибка 97 при добавлении карты

### ISSUE THREAD

**Issue by 1km** [zenmoney/ZenPlugins#494]
При попытке добавить карты альфа-банк появляется сообщение 97
"Неверный номер карты, срок ее действия или номер телефона."
на android телефоне работало нормально

iphone 6s 13.3
ZM 4.2.0.337

**Comment by skvav** [comment]
Добрый день! Спасибо за сообщение о баге. Внесли правки, сейчас должно работать.
