### ISSUE TITLE
[Альфабанк BY] каждая синхронизация создает корректировку

### ISSUE THREAD

**Issue by yahorbukhta** [zenmoney/ZenPlugins#510]
При попытке синхронизации каждый раз создается корректировка вместо некоторых новых транзакций,  а те, что добавляются-без комментариев, поэтому не устанавливается категория, началось все с самого начала, как начала работать синхронизация с этим банком.

**Comment by skvav** [comment]
Альфа-банк не сразу выкатил названия мест в апи, потому некоторые операции были без них. Сейчас должно все работать как надо. Если будут ошибки - пришлите пожалуйста лог синхронизации с приложенным описанием, по каким счетам что и как не работает.
