### ISSUE TITLE
[sberbank-online] Плагин Сбербанка был удалён

### ISSUE THREAD

**Issue by Vovan-VE** [zenmoney/ZenPlugins#533]
Здравствуйте.

Я являюсь разработчиком Домашней Бухгалтерии cubux.net. Когда-то в прошлом мы использовали исходники вашего плагина `sberbank-online` в роли документации АПИ Сбербанка, если можно так выразиться. В целом всё основное, что нам нужно, работало успешно.

Примерно 26.05.2020 это АПИ перестало отдавать нужные данные. АПИ успешно даёт авторизовываться, но когда дело доходит до получения полезных данных, оно всегда отвечает в своём стиле т.н. "временной ошибкой" №3. Так продолжается и по сей день.

Вскоре после этого я обнаружил, что вы удалили сабжевый плагин, причём как-то необъяснимо в рамках рефакторинга:
https://github.com/zenmoney/ZenPlugins/commit/bbc7469ebb870a05d419cd48b68001f3b0457d75#diff-a64fa272d62380e8a45782afd6948bc8
Я подумал, мол, наверно, случайно вышло, сейчас вернут через какое-то время. Но нет.

В то же время ваша техподдержка сообщает, что синхронизация со сбером у вас продолжает работать. Тут я могу лишь предполагать, как так получается. Но из этого почти наверняка следует то, что где-то в АПИ что-то поменялось, из-за чего оно перестало работать. Только ничего не известно, где и что не так. Информационный вакуум.

Пожалуйста, пролейте хоть какой-то свет на данную проблему и/или обстоятельства упомянутых событий, если это возможно.

**Comment by jonny3D** [comment]
В открытом доступе остаются те подключения к банкам, в разработке которых принимают участие пользователи Дзен-мани. До этого код подключений мы предоставляли открыто с прицелом, что участие в их разработке будет взаимным. К сожалению, этого не произошло. Наоборот начали использовать их в своих целях, представляя за свои, в том числе и в коммерческих продуктах.
Прим.: Речь не о вас, но результат такой. Увы.

**Comment by zpvision** [comment]
Добрый день!
Да, ваша идея действительно была отличная. Мы (cubux) предлагали функционал бесплатно, хоть и без ссылки на вас :)
Мы связывались с Fintech API Сбербанка, и, как нам сказали, публичного API для счетов физ лиц нет (только для юрлиц). Но учитывая, что у вас работает все, значит каким то образом вы подключились :)

На самом деле я мечтал о некой партнерской ассоциации для сервисов как у нас с вами, возможно еще CoinKeeper пригласить. Мы все конкуренты, но вместе мы можем развиваться быстрее, распределяя работу, чтобы не изобретать велосипед каждому.
Напишите на info@cubux.net  ваш номер, и можем обсудить более детально в мессенджерах.
