### ISSUE TITLE
[solutionbank] Ошибка обработки транзакции где в получателе есть точка-с-запятой

### ISSUE THREAD

**Issue by alparo** [zenmoney/ZenPlugins#535]
Транзакция с получаетелем "UDEMY; ONLINE COURSES; SAN FRANCISC; US" сломала парсинг и синхронизация больше не работает. Лог отправил разработчикам через функцию "отправить лог".

**Comment by vetheslav** [comment]
Фикс здесь: https://github.com/zenmoney/ZenPlugins/pull/536

**Comment by skvav** [comment]
@vetheslav спасибо! Выложили в прод
