### ISSUE TITLE
[solutionbank] - Ошибка "необходимо установить обязательное обновление"

### ISSUE THREAD

**Issue by alparo** [zenmoney/ZenPlugins#538]
Синхронизация снова сломалась.

Версия плагина 23.
Bank message: "В связи со значительными изменениями функциональных возможностей приложения необходимо установить обязательное обновление".

Лог отправлен разработчикам.

**Comment by vetheslav** [comment]
https://github.com/zenmoney/ZenPlugins/pull/539 - fix

**Comment by alparo** [comment]
Спасибо большое! Заработало. Пришлось только переподключить к банку.
