### ISSUE TITLE
Невозможно зайти в Приорбанк, Беларусь

### ISSUE THREAD

**Issue by UHanczar** [zenmoney/ZenPlugins#541]
С 06.11.2020 не работает синхронизация с Приорбанк, Беларусь. До 9.11.2020 возвращалась ошибка 72. С 09.11.2020 возвращает ошибку Приорбанк [73]. Infinity of NaN: NaN

**Comment by dhvcc** [comment]
До сих пор актуально? Приор пару раз падал в декабре того года, может, из-за этого

**Comment by uhanchar** [comment]
Нет, проблему пофиксили еще в декабре, с тех ошибок синхронизации не наблюдал
