### ISSUE TITLE
ZenPlugin swedbank-lv Ошибка синхронизации

### ISSUE THREAD

**Issue by michael-sorokin** [zenmoney/ZenPlugins#546]
Добрый день!

С 01.12.2020 перестала работать синхронизация со Swedbak LV, хотя еще 30.11.2020 работала.
Я отправил вам логи через приложение Zenmoney с указанием своего обратнога адреса

В конце лога ошибка "unexpected getLogin response"

![ZenMoney](https://user-images.githubusercontent.com/56068268/100864980-6c848280-349f-11eb-95ea-e90782bf2b7b.JPG)

**Comment by skvav** [comment]
Почили, спасибо
