### ISSUE TITLE
[mtbank] ошибка Infinity or NaN: NaN

### ISSUE THREAD

**Issue by alparo** [zenmoney/ZenPlugins#549]
Логи вчера отправил на саппорт.

**Comment by PavelSakharchuk** [comment]
I have two accounts.
One of them also has this issue.
I tried:
- re-login to mtb
- re-connected in the zen;
- updated password in the mtb.
But issue didn't disappeared.

Second MTB account doesn't have this issue.

**Comment by Barok88** [comment]
Такая же проблема. Есть какое-либо решение? 4 дня не работает синхронизация...

**Comment by Barok88** [comment]
> Такая же проблема. Есть какое-либо решение? 4 дня не работает синхронизация...

Кажется нашел причину, после чего возникла ошибка. Дело в переводе на карту другого банка, когда возникла еще дополнительная комиссия. Внес эту операцию вручную, заново подключил банк и синхронизация заработала

**Comment by PavelSakharchuk** [comment]
> > Такая же проблема. Есть какое-либо решение? 4 дня не работает синхронизация...
> 
> Кажется нашел причину, после чего возникла ошибка. Дело в переводе на карту другого банка, когда возникла еще дополнительная комиссия. Внес эту операцию вручную, заново подключил банк и синхронизация заработала

Looks like it, but I have only the transfers without commission last time.

**Comment by Barok88** [comment]
> > > Такая же проблема. Есть какое-либо решение? 4 дня не работает синхронизация...
> > 
> > 
> > Кажется нашел причину, после чего возникла ошибка. Дело в переводе на карту другого банка, когда возникла еще дополнительная комиссия. Внес эту операцию вручную, заново подключил банк и синхронизация заработала
> 
> Looks like it, but I have only the transfers without commission last time.

Nevertheless, after I entered this operation manually, the synchronization started working. Perhaps the problem is in the translations

**Comment by alparo** [comment]
Я написал в поддержку через встроенный в приложение чат. Сказали, что занимаются.

Попробовал добавить вручную транзакцию перевода на карту Беларусбанка с комиссией - не помогло. Странно, что в выписке из МТБанка комиссия отдельной транзакцией значится как 0р. Хотя если скачать чек самого перевода, то комиссия в чеке указана, как 4р. Возможно, эта транзакция с нулевой стоимостью ломает парсер.

**Comment by Barok88** [comment]
> Я написал в поддержку через встроенный в приложение чат. Сказали, что занимаются.
> 
> Попробовал добавить вручную транзакцию перевода на карту Беларусбанка с комиссией - не помогло. Странно, что в выписке из МТБанка комиссия отдельной транзакцией значится как 0р. Хотя если скачать чек самого перевода, то комиссия в чеке указана, как 4р. Возможно, эта транзакция с нулевой стоимостью ломает парсер.

Внеси все транзакции за этот день, где был перевод, удали банк из счетов и добавь заново со следующего дня, должно все пойти по новой. Я тоже отправлял в первый же день логи, но надоело ждать, стал сам анализировать после чего сломалось

**Comment by PavelSakharchuk** [comment]
> > Такая же проблема. Есть какое-либо решение? 4 дня не работает синхронизация...
> 
> Кажется нашел причину, после чего возникла ошибка. Дело в переводе на карту другого банка, когда возникла еще дополнительная комиссия. Внес эту операцию вручную, заново подключил банк и синхронизация заработала

I tried your decision. It works for me.
Thank you a lot.

**Comment by Barok88** [comment]
> > > Такая же проблема. Есть какое-либо решение? 4 дня не работает синхронизация...
> > 
> > 
> > Кажется нашел причину, после чего возникла ошибка. Дело в переводе на карту другого банка, когда возникла еще дополнительная комиссия. Внес эту операцию вручную, заново подключил банк и синхронизация заработала
> 
> I tried your decision. It works for me.
> Thank you a lot.

Уважаемый разработчик плагина, обрати на это внимание. Причина ошибки найдена, сделай чтобы она не повторялась вновь

**Comment by skvav** [comment]
Поправили, добавили пропуск операций с нулевыми суммами
