### ISSUE TITLE
[Belinvestbank] Дубликаты

### ISSUE THREAD

**Issue by Vozf** [zenmoney/ZenPlugins#551]
Дублируются транзакции после их изменения. Начало происходить после https://github.com/zenmoney/ZenPlugins/commit/684e19260059e332215678614e88fcac9bd4bb70 коммита.
Воспроизводится так - обновляем транзакции, изменяем категорию транзакции, обновляем транзакции. Получаем 2 транзакции с разными категориями. Одной нашей измененной и второй дефолтной с банка

**Comment by skvav** [comment]
Спасибо. Не очень ясно, как связано это с этим коммитом. Знак операций и сумма одинаковые в дублях?

**Comment by Vozf** [comment]
Какой-то магией починилось дня 2 назад
