### ISSUE TITLE
СМС коды Беларусбанк

### ISSUE THREAD

**Issue by dhvcc** [zenmoney/ZenPlugins#553]
Авторизация Беларусбанка может быть через **карту кодов** или **смс-код**. Только вот карты кодов боле не выпускаются

Хочу написать обработку этих кодов для автоматической синхронизации, так как доступ к СМС вроде есть

Пока не читал все доки, хотелось бы услышать комментарии или линки на примеры кода по поводу этой фичи

**Comment by vetheslav** [comment]
Карта кодов осталась в основном для клиентов, которые до сих пор такую карту имеет.
А вот с iOS нет возможности автоматически читать sms, поэтому обработка и не делается автоматически.
+ в таком случае может упасть доверие к приложению, т.к. обычно такие коды приходят туда же, где проводится 3D-Secure авторизация при оплатах. В таком случае люди могут думать что приложение может автоматически списывать деньги с карточек.
Поэтому на сколько я знаю, ZenMoney не читает смс коды по принципиальной позиции.

**Comment by dhvcc** [comment]
> Карта кодов осталась в основном для клиентов, которые до сих пор такую карту имеет.
> А вот с iOS нет возможности автоматически читать sms, поэтому обработка и не делается автоматически.
> 
>     * в таком случае может упасть доверие к приложению, т.к. обычно такие коды приходят туда же, где проводится 3D-Secure авторизация при оплатах. В таком случае люди могут думать что приложение может автоматически списывать деньги с карточек.
>       Поэтому на сколько я знаю, ZenMoney не читает смс коды по принципиальной позиции.

Да, позиция звучит логично. Жаль, конечно, можно было бы сделать опциональный флаг

Тогда остаётся ждать того, что сделает Беларусбанк вместо карт кодов
