### ISSUE TITLE
Ошибка синхронизации с РРБ банком

### ISSUE THREAD

**Issue by alexeynesteruk** [zenmoney/ZenPlugins#565]
Подсключение и загрузка транзакций проходит штатно, а вот синхронизация падает: 
![IMG_3633814F6D7E-1](https://user-images.githubusercontent.com/8975647/111973874-fd936e00-8b0f-11eb-82e8-886cff71f321.jpeg)
пофиксай плиз или посоветуй, как потестить именно формирование и применение movements?

**Comment by skvav** [comment]
Спасибо!
