### ISSUE TITLE
[forwardbank] android: краш после сабмита кнопки "подключить"

### ISSUE THREAD

**Issue by Wapweb** [zenmoney/ZenPlugins#620]
После заполнение формы и нажатия кнопки "подключить" приложение крашится. Баг репорт отправил
![Screenshot_20220114-212312](https://user-images.githubusercontent.com/8421581/149574588-bb698aac-06a8-4bb5-b131-b23920b58f2a.png)

OS: Android 8
App version: 6.9.1.778

**Comment by Wapweb** [comment]
На IOS коннект и синхронизация работает к стати. Баг воспроизводится на Android только

**Comment by skvav** [comment]
Да, есть баг в приложении. Попробуйте, пожалуйста, на последней бета-версии: https://t.me/zenmoneychat/123314
