### ISSUE TITLE
[bnbbank] Операции создаются с местом платежа BLR MINSK

### ISSUE THREAD

**Issue by alparo** [zenmoney/ZenPlugins#658]
Довольно многие операции создаются в ДМ с одним и тем же местом платежа "BLR MINSK". Это очень неудобно, потому что невозможно определить к какой категории их относить. Если я правильно понимаю, то с таким местом платежа появляются транзакции, которые еще не были обработаны банком. У них в выписке из банка есть только дата операции, но еще нет даты транзакции. 
Возможно, имеет смысл не добавлять операции, у которых нет даты транзакции чтобы потом вручную не назначать им категории? Но тогда, как я понимаю, придется ждать по несколько дней и мириться с корректировкой по счету. 
Готов как-нибудь помогать с разработкой плагина, так как очень заинтересован, чтобы связь с БНБ банком работала как надо. Программировать не умею. Могу тестировать и задонейтить немного.

**Comment by jonny3D** [comment]
@alparo Пришлите, пожалуйста, логи синхронизации с банком сразу после проведения операции и после акцепта, когда в операции появляется торговая точка места проведения платежа. Напишите об этом нам так же в чате приложения, пожалуйста, из раздела Ещё.

Подробно о том как выслать лог мы постарались расписать в нашей Базе Знаний, загляните, пожалуйста:  https://support.zenmoney.ru/knowledge-bases/2/articles/146-oshibki-podklyucheniya-k-bankam-napryamuyu

**Comment by alexeynesteruk** [comment]
> Довольно многие операции создаются в ДМ с одним и тем же местом платежа "BLR MINSK". Это очень неудобно, потому что невозможно определить к какой категории их относить. Если я правильно понимаю, то с таким местом платежа появляются транзакции, которые еще не были обработаны банком. У них в выписке из банка есть только дата операции, но еще нет даты транзакции.
> Возможно, имеет смысл не добавлять операции, у которых нет даты транзакции чтобы потом вручную не назначать им категории? Но тогда, как я понимаю, придется ждать по несколько дней и мириться с корректировкой по счету.
> Готов как-нибудь помогать с разработкой плагина, так как очень заинтересован, чтобы связь с БНБ банком работала как надо. Программировать не умею. Могу тестировать и задонейтить немного.

проблема осталась? Не думаю, что это норм ждать пока операция пройдёт по счёту а с местом, Вы бы хотели название торговой точки?

**Comment by alparo** [comment]
@alexeynesteruk после 13 сентября 2022 проблема больше не возникала. Периодически все еще появляются корректировки из ниоткуда, но, наверно, это не связано именно с этой проблемой.
А названия торговых точек теперь всегда как надо добавляются. Пожалуй, этот тикет можно закрывать.
