### ISSUE TITLE
[apelsin-uz] Интеграция развалилась с требованием обновить приложение

### ISSUE THREAD

**Issue by Bounz** [zenmoney/ZenPlugins#707]
Развалилась интеграция с Apelsin/Uzum Bank. При попытках авторизации плагин падает, в логах есть сообщение об ошибке от сервера с требованием обновить версию приложения.

**Comment by thallkeer** [comment]
А есть понимание где можно узнать актуальную версию?

**Comment by Bounz** [comment]
Расковырял трафик, там в целом изменилась схема аутентификации, теперь сначала надо на id.uzum.uz получить access-token, а потом использовать его как bearer токен.
