### ISSUE TITLE
[raiffeisen-rs] Invalid transaction - opIncome and opOutcome must have the same sign as income and outcome

### ISSUE THREAD

**Issue by luzhkovvv** [zenmoney/ZenPlugins#747]
Sync fails for raiffeisen-rs integration due to the error
```
[ZP] Exception: — [TSZ] Invalid transaction 10822637459181#3#81#336730037740. opIncome and opOutcome must have the same sign as income and outcome
```
The transaction in question (I see no way to extract the full log on iOS, so only one transaction data from screenshot):
```
{ hold: false,
date: Fri May 10 2024 00:00:00 GMT+0200 (Central
European Summer Time), movements:
[{id: 10822637459181#3#81#336730037740',
account: { id: 265022000008421126EUR' },
invoice: { sum: -1, instrument: 'MKD' },
sum: 0.02,
fee: 0}], merchant:
{ fullTitle: 'JP DRZAVNI PATISTA MKD SKOPJE,
mcc: null,
location: null },
comment: null }
```
The transaction is either an expense or refund (there were both) of 1 MKD on the EUR account.
I tried to "send log" from the app but got no answer.

update:
above transaction is a refund, the expense transaction is processed ok (I guess, if a log is parsed sequentially, as the expense transaction precedes refund one in the log):
```
{ hold: false,
date: Fri May 10 2024 00:00:00 GMT+0200 (Central
European Summer Time), movements:
Ifid: 10826952229181#4#81#336747553552',
account: { id: '265022000008421126EUR' },
invoice: { sum: -1, instrument: 'MKD' },
sum: -0.02,
fee: 0}], merchant:
{ fullTitle: 'JP DRZAVNI PATISTA MKD SKOPJE',
mcc: null,
location: null },
comment: null },
```
Looks like refund transactions have the same "invoice" as the original ones, but the sum is inverted.

**Comment by luzhkovvv** [comment]
It's 3 months and no fix!!! Another refund and again sync broken with "opIncome and opOutcome must have the same sign as income and outcome" error. I was not able to use the app for a month till the operation fell away from the sync window, now again???

**Comment by nik-bes** [comment]
@sergeykochanov Привет!
Присоединяюсь, у меня так же сломалось на рефанде

**Comment by sergeykochanov** [comment]
Ребят, ну взяли бы да починили :) я постараюсь на выходных посмотреть, но не обещаю.

**Comment by luzhkovvv** [comment]
Так тут просто скрипт прочитать недостаточно, надо знать как само приложение работает и какие данные требует. Скрипт как я понимаю все правильно разбирает, но операция с отрицательным знаком а в ней инвойс с положительным, и zenmoney это не устраивает. Как правильно поступить - насильно в скрипте приводить инвойс к знаку операции? Или может само приложение должно это правильно воспринимать... Я не знаю :)

**Comment by sergeykochanov** [comment]
Сделал вероятный фикс, но надо ждать, пока мейтейнер заапрувит.

**Comment by luzhkovvv** [comment]
починилось, спасибо! (или транзакция из окна синхронизации ушла, но вроде рановато :) )

**Comment by sergeykochanov** [comment]
Не, фикс еще не влили, так что само прошло.
