### ISSUE TITLE
[apelsin-uz] Снова развалилась интеграция с требованием обновить приложение

### ISSUE THREAD

**Issue by Bounz** [zenmoney/ZenPlugins#751]
Развалилась интеграция с Apelsin/Uzum Bank. При попытках авторизации плагин падает, в логах есть сообщение об ошибке от сервера с требованием обновить версию приложения.

**Comment by Bounz** [comment]
Пофикшено.

**Comment by agitaev** [comment]
Интеграция снова поломалась с аналогичной ошибкой обновить версию приложения.
Я могу помочь это исправить, только не могу понять откуда вот [эта версия](https://github.com/zenmoney/ZenPlugins/blob/2c639735c43479bab5d1bb6b9208477070c9352c/src/plugins/apelsin-uz/api.js#L15) берётся – `okhttp` нашёл, но что такое `Av`?

**Comment by Bounz** [comment]
Завел багулю https://github.com/zenmoney/ZenPlugins/issues/778 и PR https://github.com/zenmoney/ZenPlugins/pull/779.
`AvXXX` — эта строка передается в заголовках `app-version` в запросах к `https://mobile.apelsin.uz/api/`.
