### ISSUE TITLE
No plugin for Bank of Georgia despite integration is being supported in the app

### ISSUE THREAD

**Issue by Bobronium** [zenmoney/ZenPlugins#756]
First of all, thank you for the awesome app and plugin system, @skvav. It's something I dreamed of for a long time and found it just by accident not so long ago.

---

I noticed that while there is integration with **Bank of Georgia (BoG)** in the app, there is no corresponding source code in this repository. 

I am interested in adding a plugin to support **BoG Business**. Having access to the existing **BoG integration** code would significantly simplify the process of figuring out authentication, retrieving transactions, and mapping them correctly to ZenMoney's format.

Are there any legal issues preventing you from uploading the **BoG integration** source code? If so, how can I contribute to the **BoG Business** integration and reference the existing integration?

Feel free to contact me at `appkiller16@gmail.com` if this is not a matter for public discussion.

---

Thank you for your attention and for providing this great platform for community contributions.

**Comment by skvav** [comment]
Hi! Thank you for your interest! At your request, we decided to make the BoG plugin public. You can find it here https://github.com/zenmoney/ZenPlugins/tree/master/src/plugins/bankofgeorgia-ge
