### ISSUE TITLE
Add OAuth 2.0 support for /v2/transaction

### ISSUE THREAD

**Issue by Serg046** [zenmoney/ZenPlugins#86]
As I understand the app registration script provides keys for OAuth 2.0 now. But `/v2/transaction` api uses OAuth 1.0 authorization engine.

**Comment by skvav** [comment]
Keys are the same for both OAuth protocol versions.  But anyway /v2/transaction/ is deprecated and not  recommended for usage.

**Comment by Serg046** [comment]
No, I can use `/v8/diff/` then. Thank you!
